In [8]:
import requests

In [29]:

headers= {'Cookie': 'lang=fr; acceptcookies=1; nb_resultats_par_page=10; derniere_recherche=%7B%22produit%22%3A%22location%22%2C%22typesbien%22%3A%5B%22appartement%22%5D%2C%22nb_pieces%22%3A%7B%22min%22%3Anull%2C%22max%22%3Anull%7D%2C%22nb_chambres%22%3A%7B%22min%22%3Anull%2C%22max%22%3Anull%7D%2C%22prix%22%3A%7B%22min%22%3Anull%2C%22max%22%3Anull%7D%2C%22surface%22%3A%7B%22min%22%3Anull%2C%22max%22%3Anull%7D%2C%22surface_terrain%22%3A%7B%22min%22%3Anull%2C%22max%22%3Anull%7D%2C%22geo_objets%22%3A%5B439%5D%7D; cnil=1; atidvisitor=%7B%22name%22%3A%22atidvisitor%22%2C%22val%22%3A%7B%22vrn%22%3A%22-590496-%22%7D%2C%22options%22%3A%7B%22path%22%3A%22%2F%22%2C%22session%22%3A15724800%2C%22end%22%3A15724800%7D%7D; _ga=GA1.2.1535488843.1566545480; _gid=GA1.2.2016445835.1566545480; _gat=1',
'DNT': '1',
'Sec-Fetch-Mode': 'navigate',
'Sec-Fetch-Site': 'none',
'Sec-Fetch-User': '?1',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36'}

In [31]:
from bs4 import BeautifulSoup

In [95]:
import time
all_urls = []
for k in range(20):
    url = f'https://www.pap.fr/annonce/locations-appartement-paris-75-g439-{k}'
    html=requests.get(url, headers=headers).content
    time.sleep(2)
    soup=BeautifulSoup(html)
    insideURL = soup.select('div.col-left a[href^="/"]')
    for i in insideURL:
        all_urls.append('https://www.pap.fr' + i.get('href'))

In [96]:

headers2={'cookie': 'CONSENT=YES+FR.fr+20150705-15-0; ANID=OPT_OUT; HSID=ApMZAbapSTFtlMuMc; SSID=AfdK8DH3W3B76td3F; APISID=q2s604BHb2h-jr28/AsAkBvzWdOcaN4amn; SAPISID=qSJnlVdi1hWcvJLD/ANJqiu1fuWteInXTO; SID=mQccDQB719xk7SO8Iizjgi7PmTvXKjKJI0BZUWUnKjHUMq4x3j-jARkLyv199ERnRgxaRQ.; NID=188=kAsVBKfNVfW8lROy9e0a-U0h3B7GC3D-A2VHLriyIwJBEukWaPRCxt6AHbqmSJMtdGVEW7soQfnaMZhYs6xkxYHSSA5cl4T0ElB-1BVDX7TlmQFkGp2D1USF4XiFOHucpVAaQpUvSQQgoa7l49f6Gqs8hbiQwro1QFkzRJpT5cu3Kyk7cTfXD87JSlrp5TDbn8REkkv1pku7es3QSzPs-8Tba93KB71GYHg1lMH4bMbypbQ; 1P_JAR=2019-8-23-9; SIDCC=AN0-TYvsTQuVD_D5Xd9b6AtxU_5vWmrkoguZ_wQoQfS78Ax8VfftJDDFAdF4ja81NLMfFN-ubg',
'dnt': '1',
'sec-fetch-mode':'cors',
'sec-fetch-site':'same-origin',
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
'x-client-data': 'CJK2yQEIorbJAQjEtskBCKmdygEIqKPKAQjiqMoBCI6rygEIl63KAQjNrcoBCPKtygEIzK7KAQjKr8oB'}
names_price = []
date=[]
description=[]
for i in all_urls:
    print(i)
    html=requests.get(i,headers=headers2).content
    time.sleep(2)
    soup=BeautifulSoup(html)
    titles = [i.text for i in soup.select('h1,p')]
    names_price.append(titles[0])
    date.append(titles[1])
    description.append(titles[2])

https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r428400123
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r428300386
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r16570187
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r1814095
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r194110101
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r426601296
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r406700376
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r412002309
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r419901213
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r417301515
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r428400123
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r428300386
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r16570187
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r1814095
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r194110101
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r426601296
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r406700376
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r412002309
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r419901213
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-r417301515
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r428400505
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r16290586
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r195909243
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r423501626
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r1975011
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r197204003
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r428100621
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r419401073
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r414100165
https://www.pap.fr/annonce/locations-appartement-paris-75-g439-2-r417701054
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r424000027
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r406801850
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r409600772
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r428400524
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r428400497
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r420800397
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r428400400
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r401303697
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r420700688
https://www.pap.fr/annonce/locations-appartement-particulier-paris-75-g439-3-r422900068
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r186704101
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r428300422
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r428200274
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r197409070
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r428400259
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r427301443
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r417400797
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r410501484
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r417801012
https://www.pap.fr/annonce/immobilier-location-appartement-paris-75-g439-4-r195310755
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r417401669
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r423700246
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r427501311
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r428400366
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r418501110
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r428400554
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r428200742
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r425500478
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r417000896
https://www.pap.fr/annonce/locations-d-appartement-paris-75-g439-5-r428000207
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428000230
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428000232
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r427600854
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428400406
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428400563
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r427201154
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r418001141
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r426701454
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428400542
https://www.pap.fr/annonce/location-appart-paris-75-g439-6-r428400034
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r428400242
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r426701452
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r409601657
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r428300040
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r426101242
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r428400401
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r173504365
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r422400915
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r419600603
https://www.pap.fr/annonce/offre-location-appartement-paris-75-g439-7-r407500326
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r425601158
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r428000505
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r427601114
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r426901457
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r1991032
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r427701358
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r405502111
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r427401354
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r425700127
https://www.pap.fr/annonce/appartement-a-louer-paris-75-g439-8-r417401073
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r412500893
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r192411579
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r419900586
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r427500572
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r428400520
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r416600046
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r428400515
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r428400514
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r412800353
https://www.pap.fr/annonce/appartement-en-location-paris-75-g439-9-r403800121
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r427600298
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r425801483
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r197809996
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r427701146
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r428400500

https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r428400492
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r426800532
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r428300269
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r428400386
https://www.pap.fr/annonce/recherche-location-appartement-paris-75-g439-10-r423200295
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r428400387
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r428300562
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r428400488
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r423700685
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r427401154
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r192511049
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r428300360
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r428200311
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r175304285
https://www.pap.fr/annonce/annonce-location-appartement-paris-75-g439-11-r415901241
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428300208
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428100144
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r402301034
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428200021
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428400213
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r420100387
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r426400344
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428400458
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428200636
https://www.pap.fr/annonce/annonces-location-appartement-paris-75-g439-12-r428400453
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r428100089
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r416000128
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r427200545
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r421600789
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r428400416
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r428400534
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r1915036
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r427301581
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r427901013
https://www.pap.fr/annonce/locations-appartement-entre-particuliers-paris-75-g439-13-r427901012
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r180309814
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r415501284
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r428300472
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r406700159
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r428100732
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r427800133
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r428400407
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r428300253
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r428300348
https://www.pap.fr/annonce/location-appartements-sans-agence-paris-75-g439-14-r422101642
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r428400015
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r419600521
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r401801556
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r407300604
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r426801199
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r407601067
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r428400525
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r416800074
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r427401288
https://www.pap.fr/annonce/location-appart-particulier-paris-75-g439-15-r427700020
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r428400408
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r416501903
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r428400192
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r400301977
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r426301095
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r419800023
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r414300012
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r428200685
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r428300248
https://www.pap.fr/annonce/appart-a-louer-paris-75-g439-16-r428100007
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r418001613
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r412801282
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r428000004
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r428300246
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r428300645
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r428400002
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r417601023
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r427601376
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r426901397
https://www.pap.fr/annonce/recherche-appartement-louer-paris-75-g439-17-r407902064
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r428300634
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r196509937
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r428300458
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r421001555
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r428300330
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r428200263
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r420101075
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r418600267
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r427300243
https://www.pap.fr/annonce/appartement-a-louer-particulier-paris-75-g439-18-r428400334
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r417800547
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r428400329
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r428300449
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r408901316
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r196111423
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r414701363
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r427100732
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r414500552
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r428000667
https://www.pap.fr/annonce/offres-location-appartement-paris-75-g439-19-r423900466

In [97]:
len(names_price)

200

In [102]:
import pandas as pd
names_prices=pd.DataFrame(names_price)
dates=pd.DataFrame(date)
descriptions=pd.DataFrame(description)
locations_data=pd.concat([names_prices, dates, descriptions],axis=1)
locations_data.columns = ['Title','Date','Description']
locations_data

,Title,Date,Description
0,\n\t\t\t\tLocation meublée studio 31 m² Paris ...,Réf. : C84/0123 / 27 août 2019,"Station F. 2 min accès RER C, 900 m Tramway T3..."
1,\n\t\t\t\tLocation appartement 2 pièces 47 m² ...,Réf. : C83/0386 / 23 août 2019,F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartem...
2,\n\t\t\t\tLocation meublée appartement 3 pièce...,Réf. : 657/187 / 23 août 2019,"Daumesnil. Haussmannien, au calme, 3 pièces, 5..."
3,\n\t\t\t\tLocation appartement 2 pièces 57 m² ...,Réf. : 814/95 / 23 août 2019,"Immeuble année 2000, proche métro, bon standin..."
4,\n\t\t\t\tLocation meublée studio 20 m² Paris ...,Réf. : 941/A101 / 23 août 2019,Métro et tramway T3 Porte de Bagnolet à 5 min....
5,\n\t\t\t\tLocation appartement Paris 1Er\t\t\t...,Réf. : C66/1296 / 23 août 2019,Grand Studio (F1) au cœur de Paris. Situé au 3...
6,\n\t\t\t\tLocation meublée studio 16 m² Paris\...,Réf. : A67/0376 / 23 août 2019,Studio 16m2 Refait à neuf\r\n23 Rue Pascal au ...
7,\n\t\t\t\tLocation meublée studio 30 m² Paris ...,Réf. : B20/2309 / 23 août 2019,"Près rue mouffetard, au fond d'un grand jardin..."
8,\n\t\t\t\tLocation meublée studio 30 m² Paris ...,Réf. : B99/1213 / 23 août 2019,"Beau studio, 30 m², rez-de-chaussée sur cour, ..."
9,\n\t\t\t\tLocation meublée studio 11 m² Paris ...,Réf. : B73/1515 / 23 août 2019,Paris (75016). Pour étudiant(e)s.\n\r\nStudett...
10,\n\t\t\t\tLocation meublée studio 31 m² Paris ...,Réf. : C84/0123 / 27 août 2019,"Station F. 2 min accès RER C, 900 m Tramway T3..."
11,\n\t\t\t\tLocation appartement 2 pièces 47 m² ...,Réf. : C83/0386 / 23 août 2019,F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartem...
12,\n\t\t\t\tLocation meublée appartement 3 pièce...,Réf. : 657/187 / 23 août 2019,"Daumesnil. Haussmannien, au calme, 3 pièces, 5..."
13,\n\t\t\t\tLocation appartement 2 pièces 57 m² ...,Réf. : 814/95 / 23 août 2019,"Immeuble année 2000, proche métro, bon standin..."
14,\n\t\t\t\tLocation meublée studio 20 m² Paris ...,Réf. : 941/A101 / 23 août 2019,Métro et tramway T3 Porte de Bagnolet à 5 min....
15,\n\t\t\t\tLocation appartement Paris 1Er\t\t\t...,Réf. : C66/1296 / 23 août 2019,Grand Studio (F1) au cœur de Paris. Situé au 3...
16,\n\t\t\t\tLocation meublée studio 16 m² Paris\...,Réf. : A67/0376 / 23 août 2019,Studio 16m2 Refait à neuf\r\n23 Rue Pascal au ...
17,\n\t\t\t\tLocation meublée studio 30 m² Paris ...,Réf. : B20/2309 / 23 août 2019,"Près rue mouffetard, au fond d'un grand jardin..."
18,\n\t\t\t\tLocation meublée studio 30 m² Paris ...,Réf. : B99/1213 / 23 août 2019,"Beau studio, 30 m², rez-de-chaussée sur cour, ..."
19,\n\t\t\t\tLocation meublée studio 11 m² Paris ...,Réf. : B73/1515 / 23 août 2019,Paris (75016). Pour étudiant(e)s.\n\r\nStudett...
20,\n\t\t\t\tLocation meublée studio 21 m² Paris ...,Réf. : C84/0505 / 23 août 2019,"Dans copropriété calme et bien entretenue, stu..."
21,\n\t\t\t\tLocation meublée appartement 3 pièce...,Réf. : 629/586 / 23 août 2019,Bail meublé code civil (société ou hab.seconda...
22,\n\t\t\t\tLocation meublée studio 25 m² Paris ...,Réf. : 959/9243 / 23 août 2019,\n\t\t\t\t\tMETRO DUPLEIX - STUDIO SUR JARDIN ...
23,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : C35/1626 / 23 août 2019,"T2 meublé de 42 m², au 90 boulevard de Grenell..."
24,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : 975/11 / 23 août 2019,"Métro La Muette. Rue des Vignes. Au 3e étage, ..."
25,\n\t\t\t\tLocation appartement 2 pièces 51 m² ...,Réf. : 972/4003 / 23 août 2019,Entrée Parc Buttes Chaumont. Avenue Maturin Mo...
26,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : C81/0621 / 23 août 2019,"Métro Passy. Agréable studio environ 23 m², au..."
27,\n\t\t\t\tLocation meublée studio 14 m² Paris ...,Réf. : B94/1073 / 23 août 2019,Charmant studio meublé de 14 m² (pour une pers...
28,\n\t\t\t\tLocation meublée studio 12 m² Paris ...,Réf. : B41/0165 / 23 août 2019,Champs-Élysées.\r\nStudette exposé Sud-Ouest -...
29,\n\t\t\t\tLocation meublée chambre 13 m² Paris...,Réf. : B77/1054 / 23 août 2019,Chambre meublée pour étudiant au 6ème étage sa...
...,...,...,...
170,\n\t\t\t\tLocation meublée studio 18 m² Paris ...,Réf. : B80/1613 / 23 août 2019,Studio meublé tout confort dans bel immeuble a...
171,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : B28/1282 / 23 août 2019,Appartement meublé récemment rénové à louer.\n...
172,\n\t\t\t\tLocation meublée studio 27 m² Paris ...,Réf. : C80/0004 / 23 août 2019,"Situé dans un quartier recherché, au pied du m..."
173,\n\t\t\t\tLocation appartement 2 pièces 46 m² ...,Réf. : C83/0246 / 23 août 2019,"Appartement à 300 mètres du métro Alésia, supe..."
174,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : C83/0645 / 23 août 2019,Location appartement 38 m² : 1 séjour et chamb...
175,\n\t\t\t\tLocation meublée studio 36 m² Paris ...,Réf. : C84/0002 / 23 août 2019,"Meublée 1 an minimum, avenue Wagram (8ème Pari..."
176,\n\t\t\t\tLocation meublée chambre 10 m² Paris...,Réf. : B76/1023 / 23 août 2019,1 pièce 1 chambre 10 m²\r\nChambre meublée d...
177,\n\t\t\t\tLocation meublée appartement 4 pièce...,Réf. : C76/1376 / 23 août 2019,"Appartement 70 m², immeuble haussmannien, 3e ..."
178,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : C69/1397 / 22 août 2019,"Proche Beaubourg, métro Rambuteau.\n\r\n1er ét..."
179,\n\t\t\t\tLocation meublée studio 48 m² Paris ...,Réf. : A79/2064 / 22 août 2019,Large studio avec terrasse - entièrement rénov...
180,\n\t\t\t\tLocation appartement 3 pièces 59 m² ...,Réf. : C83/0634 / 22 août 2019,"Très bel appartement de grand standing, situé ..."
181,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : 965/9937 / 22 août 2019,Superbe 2 pièces 50 m². Rue St-Paul. Ascenseur...
182,\n\t\t\t\tLocation meublée studio 21 m² Paris ...,Réf. : C83/0458 / 22 août 2019,"Rue Greuze. Immeuble Haussmannien, de grand st..."
183,\n\t\t\t\tLocation studio 16 m² Paris 17E\t\t\...,Réf. : C10/1555 / 22 août 2019,Monceau ou Malesherbes.\r\nImmeuble de très bo...
184,Accès bloqué,Votre accès au site PAP.fr a été bloqué\r\n\t\...,"Pour obtenir le déblocage de votre accès, veui..."
185,\n\t\t\t\tLocation appartement 3 pièces 75 m² ...,Réf. : C82/0263 / 22 août 2019,"Côté Marais / Place des Vosges,\r\ndans réside..."
186,\n\t\t\t\tLocation meublée studio 29 m² Paris ...,Réf. : C01/1075 / 22 août 2019,Confortable studio meublé refait à neuf par un...
187,\n\t\t\t\tLocation meublée studio 14 m² Paris ...,Réf. : B86/0267 / 22 août 2019,"Propose en bail mobilité, agréable studio meub..."
188,\n\t\t\t\tLocation appartement 2 pièces 52 m² ...,Réf. : C73/0243 / 22 août 2019,"Rue des Beaux-Arts, au coeur du quartier Saint..."
189,\n\t\t\t\tLocation meublée studio 25 m² Paris ...,Réf. : C84/0334 / 22 août 2019,PARIS 75012 Studio meublé de 25 m² refait à ne...
190,\n\t\t\t\tLocation meublée studio 35 m² Paris ...,Réf. : B78/0547 / 22 août 2019,Studio de 35 m² meublé et équipé a louer penda...
191,\n\t\t\t\tLocation meublée studio 10 m² Paris ...,Réf. : C84/0329 / 22 août 2019,A louer à compter du 1er septembre une studett...
192,\n\t\t\t\tLocation appartement 2 pièces 33 m² ...,Réf. : C83/0449 / 22 août 2019,Deux pièces double exposition.\n\r\nEntrée ave...
193,\n\t\t\t\tLocation meublée appartement 3 pièce...,Réf. : A89/1316 / 22 août 2019,\n\t\t\t\t\tBeau 3 pièces meublé\t\t\t\t
194,\n\t\t\t\tLocation meublée studio 14 m² Paris\...,Réf. : 961/B423 / 22 août 2019,Au cœur du marché de Levis (46 rue de Levis). ...
195,\n\t\t\t\tLocation appartement 2 pièces 30 m² ...,Réf. : B47/1363 / 22 août 2019,"Paris 15e.\n\r\nMetro Vaugirard/Commerce, derr..."
196,Accès bloqué,Votre accès au site PAP.fr a été bloqué\r\n\t\...,"Pour obtenir le déblocage de votre accès, veui..."
197,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : B45/0552 / 22 août 2019,"Appartement meublé, quartier calme, bel immeub..."
198,\n\t\t\t\tLocation meublée appartement 3 pièce...,Réf. : C80/0667 / 22 août 2019,3/4 pièces. Appartement meublé 65 m² sans vis-...
199,\n\t\t\t\tLocation meublée appartement 2 pièce...,Réf. : C39/0466 / 22 août 2019,Appartement meublé de 35 m² au deuxième étage ...

In [116]:
names_prices

                                                     0
0    \n\t\t\t\tLocation meublée studio 31 m² Paris ...
1    \n\t\t\t\tLocation appartement 2 pièces 47 m² ...
2    \n\t\t\t\tLocation meublée appartement 3 pièce...
3    \n\t\t\t\tLocation appartement 2 pièces 57 m² ...
4    \n\t\t\t\tLocation meublée studio 20 m² Paris ...
5    \n\t\t\t\tLocation appartement Paris 1Er\t\t\t...
6    \n\t\t\t\tLocation meublée studio 16 m² Paris\...
7    \n\t\t\t\tLocation meublée studio 30 m² Paris ...
8    \n\t\t\t\tLocation meublée studio 30 m² Paris ...
9    \n\t\t\t\tLocation meublée studio 11 m² Paris ...
10   \n\t\t\t\tLocation meublée studio 31 m² Paris ...
11   \n\t\t\t\tLocation appartement 2 pièces 47 m² ...
12   \n\t\t\t\tLocation meublée appartement 3 pièce...
13   \n\t\t\t\tLocation appartement 2 pièces 57 m² ...
14   \n\t\t\t\tLocation meublée studio 20 m² Paris ...
15   \n\t\t\t\tLocation appartement Paris 1Er\t\t\t...
16   \n\t\t\t\tLocation meublée studio 16 m² Paris\...
17   \n\t\t\t\tLocation meublée studio 30 m² Paris ...
18   \n\t\t\t\tLocation meublée studio 30 m² Paris ...
19   \n\t\t\t\tLocation meublée studio 11 m² Paris ...
20   \n\t\t\t\tLocation meublée studio 21 m² Paris ...
21   \n\t\t\t\tLocation meublée appartement 3 pièce...
22   \n\t\t\t\tLocation meublée studio 25 m² Paris ...
23   \n\t\t\t\tLocation meublée appartement 2 pièce...
24   \n\t\t\t\tLocation meublée appartement 2 pièce...
25   \n\t\t\t\tLocation appartement 2 pièces 51 m² ...
26   \n\t\t\t\tLocation meublée appartement 2 pièce...
27   \n\t\t\t\tLocation meublée studio 14 m² Paris ...
28   \n\t\t\t\tLocation meublée studio 12 m² Paris ...
29   \n\t\t\t\tLocation meublée chambre 13 m² Paris...
..                                                 ...
170  \n\t\t\t\tLocation meublée studio 18 m² Paris ...
171  \n\t\t\t\tLocation meublée appartement 2 pièce...
172  \n\t\t\t\tLocation meublée studio 27 m² Paris ...
173  \n\t\t\t\tLocation appartement 2 pièces 46 m² ...
174  \n\t\t\t\tLocation meublée appartement 2 pièce...
175  \n\t\t\t\tLocation meublée studio 36 m² Paris ...
176  \n\t\t\t\tLocation meublée chambre 10 m² Paris...
177  \n\t\t\t\tLocation meublée appartement 4 pièce...
178  \n\t\t\t\tLocation meublée appartement 2 pièce...
179  \n\t\t\t\tLocation meublée studio 48 m² Paris ...
180  \n\t\t\t\tLocation appartement 3 pièces 59 m² ...
181  \n\t\t\t\tLocation meublée appartement 2 pièce...
182  \n\t\t\t\tLocation meublée studio 21 m² Paris ...
183  \n\t\t\t\tLocation studio 16 m² Paris 17E\t\t\...
184                                       Accès bloqué
185  \n\t\t\t\tLocation appartement 3 pièces 75 m² ...
186  \n\t\t\t\tLocation meublée studio 29 m² Paris ...
187  \n\t\t\t\tLocation meublée studio 14 m² Paris ...
188  \n\t\t\t\tLocation appartement 2 pièces 52 m² ...
189  \n\t\t\t\tLocation meublée studio 25 m² Paris ...
190  \n\t\t\t\tLocation meublée studio 35 m² Paris ...
191  \n\t\t\t\tLocation meublée studio 10 m² Paris ...
192  \n\t\t\t\tLocation appartement 2 pièces 33 m² ...
193  \n\t\t\t\tLocation meublée appartement 3 pièce...
194  \n\t\t\t\tLocation meublée studio 14 m² Paris\...
195  \n\t\t\t\tLocation appartement 2 pièces 30 m² ...
196                                       Accès bloqué
197  \n\t\t\t\tLocation meublée appartement 2 pièce...
198  \n\t\t\t\tLocation meublée appartement 3 pièce...
199  \n\t\t\t\tLocation meublée appartement 2 pièce...

[200 rows x 1 columns]

In [118]:
title_list=[i.strip().replace('\xa0', '').replace('\t', ' ').lstrip('Location') for i in locations_data.Title.tolist()]

In [176]:
import re
price_list=[]
for i in title_list:
    try:
        match=re.search(r'(\d?\.?\d+)€', i).group(1)
    except:
        match='-1'
    price_list.append(match)

price_list1=[int(i.replace('.','')) for i in price_list]
    
price_list1

[1390,
 1412,
 1533,
 1950,
 760,
 990,
 820,
 1200,
 1185,
 540,
 1390,
 1412,
 1533,
 1950,
 760,
 990,
 820,
 1200,
 1185,
 540,
 780,
 2370,
 1350,
 1700,
 1295,
 1500,
 1190,
 700,
 699,
 650,
 1280,
 690,
 540,
 850,
 1180,
 1290,
 850,
 500,
 850,
 1200,
 3500,
 1037,
 1275,
 1900,
 997,
 1000,
 1100,
 1260,
 1045,
 1150,
 950,
 830,
 1650,
 1850,
 2200,
 900,
 1149,
 2490,
 1350,
 1050,
 1050,
 1950,
 1800,
 1900,
 980,
 1700,
 1670,
 570,
 650,
 1380,
 1650,
 2100,
 1650,
 2150,
 1750,
 2600,
 795,
 1890,
 1550,
 1990,
 1800,
 1200,
 2800,
 1700,
 720,
 3600,
 1410,
 1500,
 1390,
 540,
 2300,
 860,
 2160,
 965,
 500,
 900,
 605,
 1990,
 2850,
 1150,
 600,
 2370,
 840,
 2200,
 815,
 1000,
 900,
 850,
 500,
 1200,
 535,
 640,
 2450,
 2950,
 1290,
 1400,
 1310,
 860,
 1200,
 1600,
 2370,
 1420,
 880,
 1990,
 990,
 900,
 3000,
 2300,
 2425,
 930,
 1500,
 1150,
 1950,
 790,
 1090,
 595,
 1597,
 1575,
 1400,
 1395,
 1020,
 1180,
 600,
 2900,
 1670,
 980,
 1460,
 1400,
 692,
 1200,
 800,
 680,
 1300,
 595,
 1550,
 1080,
 1218,
 960,
 2190,
 1280,
 720,
 1800,
 1070,
 475,
 1100,
 850,
 2350,
 1350,
 1440,
 2500,
 1080,
 1685,
 1150,
 1450,
 1600,
 1100,
 530,
 2500,
 1950,
 1800,
 2400,
 2390,
 1030,
 820,
 -1,
 2450,
 1300,
 800,
 2400,
 809,
 1100,
 550,
 1100,
 2115,
 850,
 1120,
 -1,
 1599,
 2450,
 1650]

In [127]:
title_list

[' meublée studio 31m² Paris 13E    1.390€',
 ' appartement 2pièces 47m² Paris 20E    1.412€',
 ' meublée appartement 3pièces 53m² Paris    1.533€',
 ' appartement 2pièces 57m² Paris 11 Pere Lachaise    1.950€',
 ' meublée studio 20m² Paris 20E    760€',
 ' appartement Paris 1Er    990€',
 ' meublée studio 16m² Paris    820€',
 ' meublée studio 30m² Paris 13E    1.200€',
 ' meublée studio 30m² Paris 15E    1.185€',
 ' meublée studio 11m² Paris 16E    540€',
 ' meublée studio 31m² Paris 13E    1.390€',
 ' appartement 2pièces 47m² Paris 20E    1.412€',
 ' meublée appartement 3pièces 53m² Paris    1.533€',
 ' appartement 2pièces 57m² Paris 11 Pere Lachaise    1.950€',
 ' meublée studio 20m² Paris 20E    760€',
 ' appartement Paris 1Er    990€',
 ' meublée studio 16m² Paris    820€',
 ' meublée studio 30m² Paris 13E    1.200€',
 ' meublée studio 30m² Paris 15E    1.185€',
 ' meublée studio 11m² Paris 16E    540€',
 ' meublée studio 21m² Paris 18E    780€',
 ' meublée appartement 3pièces 74m² Paris    2.370€',
 ' meublée studio 25m² Paris 15E    1.350€',
 ' meublée appartement 2pièces 42m² Paris 15E    1.700€',
 ' meublée appartement 2pièces 31m² Paris 16E    1.295€',
 ' appartement 2pièces 51m² Paris 19E    1.500€',
 ' meublée appartement 2pièces 23m² Paris 16E    1.190€',
 ' meublée studio 14m² Paris 14E    700€',
 ' meublée studio 12m² Paris 8E    699€',
 ' meublée chambre 13m² Paris 11E    650€',
 ' meublée studio 26m² Paris 5E    1.280€',
 ' meublée studio 15m² Paris 20E    690€',
 ' studio 12m² Paris 14E    540€',
 ' meublée appartement 22m² Paris 18E    850€',
 ' appartement 2pièces 32m² Paris 14E    1.180€',
 ' meublée appartement 2pièces 34m² Paris 13E    1.290€',
 ' meublée studio 19m² Paris 14E    850€',
 ' meublée studio 13m² Paris    500€',
 ' meublée studio 15m² Paris 4E    850€',
 ' meublée studio 22m² Paris 18E    1.200€',
 ' appartement 4pièces 96m² Paris 15E    3.500€',
 ' meublée studio 28m² Paris 18E    1.037€',
 ' meublée studio 33m² Paris 5E    1.275€',
 ' meublée appartement 2pièces 46m² Paris    1.900€',
 ' meublée studio 22m² Paris 15E    997€',
 ' meublée studio 14m² Paris 2E    1.000€',
 ' meublée studio 23m² Paris 6E    1.100€',
 ' meublée studio 33m² Paris 17E    1.260€',
 ' meublée appartement 2pièces 35m² Paris 19E    1.045€',
 ' meublée studio 27m² Paris 5E    1.150€',
 ' meublée studio 21m² Paris 15E    950€',
 ' meublée studio 16m² Paris 13E    830€',
 ' meublée appartement 2pièces 43m² Paris 12E    1.650€',
 ' meublée appartement 2pièces 45m² Paris 16E    1.850€',
 ' meublée appartement 3pièces 74m² Paris 10E    2.200€',
 ' meublée studio 30m² Paris 18E    900€',
 ' meublée studio 18m² Paris 2E    1.149€',
 ' meublée appartement 3pièces 75m² Paris 3E    2.490€',
 ' meublée appartement 2pièces 36m² Paris 5E    1.350€',
 ' meublée studio 15m² Paris 6E    1.050€',
 ' meublée studio 15m² Paris 6E    1.050€',
 ' meublée appartement 2pièces 46m² Paris 6E    1.950€',
 ' meublée appartement 2pièces 51m² Paris 11E    1.800€',
 ' meublée appartement 2pièces 54m² Paris 15E    1.900€',
 ' meublée appartement 2pièces 28m² Paris 10E    980€',
 ' meublée appartement 2pièces 48m² Paris 13E    1.700€',
 ' meublée appartement 2pièces 55m² Paris 15E    1.670€',
 ' meublée studio 11m² Paris 17E    570€',
 ' meublée studio 12m² Paris 15E    650€',
 ' meublée appartement 2pièces 35m² Paris 2E    1.380€',
 ' meublée appartement 3pièces 46m² Paris 10E    1.650€',
 ' meublée appartement 2pièces 70m² Paris 11E    2.100€',
 ' meublée appartement 2pièces 48m² Paris 15E    1.650€',
 ' appartement 3pièces 73m² Paris 16E    2.150€',
 ' meublée appartement 2pièces 50m² Paris 17E    1.750€',
 ' meublée appartement 4pièces 60m² Paris 19E    2.600€',
 ' meublée studio Paris 15E    795€',
 ' meublée appartement 3pièces 60m² Paris 12E    1.890€',
 ' meublée appartement 2pièces 46m² Paris 15E    1.550€',
 ' meublée appartement 3pièces 70m² Paris 13E    1.990€',
 ' meublée studio 49m² Paris 6E    1.800€',
 ' appartement 2pièces 34m² Paris 12E    1.200€',
 ' appartement 2pièces 74m² Paris 2E    2.800€',
 ' appartement 2pièces 56m² Paris 19E    1.700€',
 ' meublée studio 14m² Paris 1Er    720€',
 ' meublée appartement 3pièces 70m² Paris 1Er    3.600€',
 ' meublée studio 26m² Paris 6E    1.410€',
 ' meublée studio 25m² Paris 16E    1.500€',
 ' meublée studio 34m² Paris 1Er    1.390€',
 ' chambre 10m² Paris 5E    540€',
 ' meublée appartement 3pièces 70m² Paris 13E    2.300€',
 ' meublée studio 27m² Paris 18E    860€',
 ' appartement 3pièces 76m² Paris 18E    2.160€',
 ' meublée studio 25m² Paris 18E    965€',
 ' meublée studio 13m² Paris 13E    500€',
 ' meublée studio 32m² Paris 16E    900€',
 ' meublée studio 15m² Paris 16E    605€',
 ' meublée appartement 3pièces 73m² Paris 13E    1.990€',
 ' meublée appartement 4pièces 81m² Paris 4E    2.850€',
 ' meublée studio 33m² Paris 16E    1.150€',
 ' meublée studio 11m² Paris 16E    600€',
 ' appartement 3pièces 69m² Paris 19E    2.370€',
 ' meublée studio 22m² Paris    840€',
 ' meublée appartement 2pièces 48m² Paris 8E    2.200€',
 ' meublée studio 19m² Paris 15E    815€',
 ' appartement 2pièces 35m² Paris 19E    1.000€',
 ' meublée studio 16m² Paris 5E    900€',
 ' meublée chambre 17m² Paris 9E    850€',
 ' meublée studio 10m² Paris 17E    500€',
 ' meublée appartement 2pièces 32m² Paris 18E    1.200€',
 ' studio 15m² Paris 18E    535€',
 ' studio 23m² Paris 19E    640€',
 ' appartement 3pièces 73m² Paris 16E    2.450€',
 ' meublée appartement 4pièces 85m² Paris 3E    2.950€',
 ' meublée studio 15m² Paris 5E    1.290€',
 ' meublée appartement 2pièces 30m² Paris 6E    1.400€',
 ' meublée appartement 2pièces 36m² Paris 6E    1.310€',
 ' meublée studio 18m² Paris 9E    860€',
 ' meublée studio 30m² Paris    1.200€',
 ' meublée appartement 2pièces 45m² Paris 16E    1.600€',
 ' meublée appartement 3pièces 69m² Paris 1Er    2.370€',
 ' appartement 2pièces 36m² Paris 7E    1.420€',
 ' meublée studio 18m² Paris 16E    880€',
 ' meublée appartement 2pièces 60m² Paris 16E    1.990€',
 ' meublée studio 22m² Paris 16E    990€',
 ' meublée studio 22m² Paris 18E    900€',
 ' appartement 4pièces 90m² Paris 13E    3.000€',
 ' appartement 3pièces 74m² Paris 16E    2.300€',
 ' meublée appartement 2pièces 67m² Paris 2E    2.425€',
 ' meublée studio 24m² Paris 11E    930€',
 ' meublée appartement 2pièces 50m² Paris 15E    1.500€',
 ' meublée studio 40m² Paris 16E    1.150€',
 ' meublée appartement 2pièces 50m² Paris 16E    1.950€',
 ' meublée chambre 16m² Paris 12E    790€',
 ' meublée studio 24m² Paris 5E    1.090€',
 ' meublée studio 15m² Paris 12E    595€',
 ' meublée studio 30m² Paris 6E    1.597€',
 ' studio 45m² Paris 14E    1.575€',
 ' meublée appartement 2pièces 35m² Paris 17E    1.400€',
 ' appartement 2pièces 50m² Paris 19E    1.395€',
 ' appartement 2pièces 36m² Paris 12E    1.020€',
 ' meublée studio 32m² Paris 3E    1.180€',
 ' meublée studio 10m² Paris 12E    600€',
 ' appartement 4pièces 105m² Paris    2.900€',
 ' appartement 2pièces 55m² Paris 17E    1.670€',
 ' meublée studio 26m² Paris 18E    980€',
 ' appartement 3pièces 46m² Paris 18E    1.460€',
 ' appartement 2pièces 41m² Paris 15E    1.400€',
 ' meublée studio 13m² Paris 16E    692€',
 ' meublée appartement 2pièces 34m² Paris 17E    1.200€',
 ' meublée studio 14m² Paris 18E    800€',
 ' meublée studio 11m² Paris 3E    680€',
 ' meublée appartement 2pièces 32m² Paris 14E    1.300€',
 ' meublée studio 9m² Paris 8E    595€',
 ' meublée appartement 2pièces 35m² Paris 17E    1.550€',
 ' meublée appartement 2pièces 30m² Paris 14E    1.080€',
 ' studio 38m² Paris 3E    1.218€',
 ' meublée studio 24m² Paris 11E    960€',
 ' meublée appartement 4pièces 63m² Paris 12E    2.190€',
 ' meublée studio 35m² Paris 14E    1.280€',
 ' studio 23m² Paris 20E    720€',
 ' meublée appartement 3pièces 52m² Paris 6E    1.800€',
 ' studio 28m² Paris 6E    1.070€',
 ' meublée chambre Paris 13E    475€',
 ' studio 40m² Paris 15E    1.100€',
 ' meublée studio 18m² Paris 4E    850€',
 ' meublée appartement 2pièces 66m² Paris 5E    2.350€',
 ' meublée appartement 2pièces 44m² Paris 14E    1.350€',
 ' meublée appartement 2pièces 43m² Paris 13E    1.440€',
 ' appartement 3pièces 86m² Paris 16E    2.500€',
 ' meublée studio 18m² Paris 16E    1.080€',
 ' meublée appartement 2pièces 51m² Paris 11E    1.685€',
 ' meublée studio 27m² Paris 17E    1.150€',
 ' appartement 2pièces 46m² Paris 14E    1.450€',
 ' meublée appartement 2pièces 38m² Paris 17E    1.600€',
 ' meublée studio 36m² Paris 8E    1.100€',
 ' meublée chambre 10m² Paris 16E    530€',
 ' meublée appartement 4pièces 70m² Paris 16E    2.500€',
 ' meublée appartement 2pièces 50m² Paris 3E    1.950€',
 ' meublée studio 48m² Paris 17E    1.800€',
 ' appartement 3pièces 59m² Paris 2E    2.400€',
 ' meublée appartement 2pièces 50m² Paris    2.390€',
 ' meublée studio 21m² Paris 16E    1.030€',
 ' studio 16m² Paris 17E    820€',
 'Accès bloqué',
 ' appartement 3pièces 75m² Paris 11E    2.450€',
 ' meublée studio 29m² Paris 12E    1.300€',
 ' meublée studio 14m² Paris 18E    800€',
 ' appartement 2pièces 52m² Paris 6E    2.400€',
 ' meublée studio 25m² Paris 12E    809€',
 ' meublée studio 35m² Paris 14E    1.100€',
 ' meublée studio 10m² Paris 13E    550€',
 ' appartement 2pièces 33m² Paris 18E    1.100€',
 ' meublée appartement 3pièces 62m² Paris 15E    2.115€',
 ' meublée studio 14m² Paris    850€',
 ' appartement 2pièces 30m² Paris 15E    1.120€',
 'Accès bloqué',
 ' meublée appartement 2pièces 47m² Paris 15E    1.599€',
 ' meublée appartement 3pièces 65m² Paris 18E    2.450€',
 ' meublée appartement 2pièces 38m² Paris 4E    1.650€']

In [178]:
location=[]
for i in title_list:
    try:
        match=re.search(r'Paris [\d+\w+]*', i).group(0)
    except:
        match='-1'
    location.append(match)
location

['Paris 13E',
 'Paris 20E',
 'Paris ',
 'Paris 11',
 'Paris 20E',
 'Paris 1Er',
 'Paris ',
 'Paris 13E',
 'Paris 15E',
 'Paris 16E',
 'Paris 13E',
 'Paris 20E',
 'Paris ',
 'Paris 11',
 'Paris 20E',
 'Paris 1Er',
 'Paris ',
 'Paris 13E',
 'Paris 15E',
 'Paris 16E',
 'Paris 18E',
 'Paris ',
 'Paris 15E',
 'Paris 15E',
 'Paris 16E',
 'Paris 19E',
 'Paris 16E',
 'Paris 14E',
 'Paris 8E',
 'Paris 11E',
 'Paris 5E',
 'Paris 20E',
 'Paris 14E',
 'Paris 18E',
 'Paris 14E',
 'Paris 13E',
 'Paris 14E',
 'Paris ',
 'Paris 4E',
 'Paris 18E',
 'Paris 15E',
 'Paris 18E',
 'Paris 5E',
 'Paris ',
 'Paris 15E',
 'Paris 2E',
 'Paris 6E',
 'Paris 17E',
 'Paris 19E',
 'Paris 5E',
 'Paris 15E',
 'Paris 13E',
 'Paris 12E',
 'Paris 16E',
 'Paris 10E',
 'Paris 18E',
 'Paris 2E',
 'Paris 3E',
 'Paris 5E',
 'Paris 6E',
 'Paris 6E',
 'Paris 6E',
 'Paris 11E',
 'Paris 15E',
 'Paris 10E',
 'Paris 13E',
 'Paris 15E',
 'Paris 17E',
 'Paris 15E',
 'Paris 2E',
 'Paris 10E',
 'Paris 11E',
 'Paris 15E',
 'Paris 16E',
 'Paris 17E',
 'Paris 19E',
 'Paris 15E',
 'Paris 12E',
 'Paris 15E',
 'Paris 13E',
 'Paris 6E',
 'Paris 12E',
 'Paris 2E',
 'Paris 19E',
 'Paris 1Er',
 'Paris 1Er',
 'Paris 6E',
 'Paris 16E',
 'Paris 1Er',
 'Paris 5E',
 'Paris 13E',
 'Paris 18E',
 'Paris 18E',
 'Paris 18E',
 'Paris 13E',
 'Paris 16E',
 'Paris 16E',
 'Paris 13E',
 'Paris 4E',
 'Paris 16E',
 'Paris 16E',
 'Paris 19E',
 'Paris ',
 'Paris 8E',
 'Paris 15E',
 'Paris 19E',
 'Paris 5E',
 'Paris 9E',
 'Paris 17E',
 'Paris 18E',
 'Paris 18E',
 'Paris 19E',
 'Paris 16E',
 'Paris 3E',
 'Paris 5E',
 'Paris 6E',
 'Paris 6E',
 'Paris 9E',
 'Paris ',
 'Paris 16E',
 'Paris 1Er',
 'Paris 7E',
 'Paris 16E',
 'Paris 16E',
 'Paris 16E',
 'Paris 18E',
 'Paris 13E',
 'Paris 16E',
 'Paris 2E',
 'Paris 11E',
 'Paris 15E',
 'Paris 16E',
 'Paris 16E',
 'Paris 12E',
 'Paris 5E',
 'Paris 12E',
 'Paris 6E',
 'Paris 14E',
 'Paris 17E',
 'Paris 19E',
 'Paris 12E',
 'Paris 3E',
 'Paris 12E',
 'Paris ',
 'Paris 17E',
 'Paris 18E',
 'Paris 18E',
 'Paris 15E',
 'Paris 16E',
 'Paris 17E',
 'Paris 18E',
 'Paris 3E',
 'Paris 14E',
 'Paris 8E',
 'Paris 17E',
 'Paris 14E',
 'Paris 3E',
 'Paris 11E',
 'Paris 12E',
 'Paris 14E',
 'Paris 20E',
 'Paris 6E',
 'Paris 6E',
 'Paris 13E',
 'Paris 15E',
 'Paris 4E',
 'Paris 5E',
 'Paris 14E',
 'Paris 13E',
 'Paris 16E',
 'Paris 16E',
 'Paris 11E',
 'Paris 17E',
 'Paris 14E',
 'Paris 17E',
 'Paris 8E',
 'Paris 16E',
 'Paris 16E',
 'Paris 3E',
 'Paris 17E',
 'Paris 2E',
 'Paris ',
 'Paris 16E',
 'Paris 17E',
 '-1',
 'Paris 11E',
 'Paris 12E',
 'Paris 18E',
 'Paris 6E',
 'Paris 12E',
 'Paris 14E',
 'Paris 13E',
 'Paris 18E',
 'Paris 15E',
 'Paris ',
 'Paris 15E',
 '-1',
 'Paris 15E',
 'Paris 18E',
 'Paris 4E']

In [179]:
m2=[]
for i in title_list:
    try:
        match=re.search(r'\d+m', i).group(0)
    except:
        match='-1'
    m2.append(match)
m2

200

In [187]:
description=[title_list[i].replace(price_list[i],'').strip('€ ').replace(location[i],'').replace(m2[i],'').replace(' ² ',' 1').replace('é', 'e') for i in range(len(title_list))]
loc_type=[]
for i in description:
    try:
        match=re.search(r'^\s*\D*', i).group(0)
    except:
        match='-1'
    loc_type.append(match)
loc_type

['meublee studio ',
 'appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee chambre ',
 'meublee studio ',
 'meublee studio ',
 'studio ',
 'meublee appartement ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'appartement ',
 'appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'chambre ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee chambre ',
 'meublee studio ',
 'meublee appartement ',
 'studio ',
 'studio ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee chambre ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'studio ',
 'meublee appartement ',
 'appartement ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'appartement ',
 'meublee studio ',
 'appartement ',
 'appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'studio ',
 'meublee appartement ',
 'studio ',
 'meublee chambre ',
 'studio ',
 'meublee studio ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ',
 'appartement ',
 'meublee studio ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'meublee chambre ',
 'meublee appartement ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'studio ',
 'Accès bloque',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'meublee studio ',
 'meublee studio ',
 'meublee studio ',
 'appartement ',
 'meublee appartement ',
 'meublee studio ',
 'appartement ',
 'Accès bloque',
 'meublee appartement ',
 'meublee appartement ',
 'meublee appartement ']

In [189]:
date=[locations_data.Date.tolist()]

['Réf. : C84/0123 /  27 août 2019',
 'Réf. : C83/0386 /  23 août 2019',
 'Réf. : 657/187 /  23 août 2019',
 'Réf. : 814/95 /  23 août 2019',
 'Réf. : 941/A101 /  23 août 2019',
 'Réf. : C66/1296 /  23 août 2019',
 'Réf. : A67/0376 /  23 août 2019',
 'Réf. : B20/2309 /  23 août 2019',
 'Réf. : B99/1213 /  23 août 2019',
 'Réf. : B73/1515 /  23 août 2019',
 'Réf. : C84/0123 /  27 août 2019',
 'Réf. : C83/0386 /  23 août 2019',
 'Réf. : 657/187 /  23 août 2019',
 'Réf. : 814/95 /  23 août 2019',
 'Réf. : 941/A101 /  23 août 2019',
 'Réf. : C66/1296 /  23 août 2019',
 'Réf. : A67/0376 /  23 août 2019',
 'Réf. : B20/2309 /  23 août 2019',
 'Réf. : B99/1213 /  23 août 2019',
 'Réf. : B73/1515 /  23 août 2019',
 'Réf. : C84/0505 /  23 août 2019',
 'Réf. : 629/586 /  23 août 2019',
 'Réf. : 959/9243 /  23 août 2019',
 'Réf. : C35/1626 /  23 août 2019',
 'Réf. : 975/11 /  23 août 2019',
 'Réf. : 972/4003 /  23 août 2019',
 'Réf. : C81/0621 /  23 août 2019',
 'Réf. : B94/1073 /  23 août 2019',
 'Réf. : B41/0165 /  23 août 2019',
 'Réf. : B77/1054 /  23 août 2019',
 'Réf. : C40/0027 /  23 août 2019',
 'Réf. : A68/1850 /  23 août 2019',
 'Réf. : A96/0772 /  23 août 2019',
 'Réf. : C84/0524 /  23 août 2019',
 'Réf. : C84/0497 /  23 août 2019',
 'Réf. : C08/0397 /  23 août 2019',
 'Réf. : C84/0400 /  23 août 2019',
 'Réf. : A13/3697 /  23 août 2019',
 'Réf. : C07/0688 /  23 août 2019',
 'Réf. : C29/0068 /  23 août 2019',
 'Réf. : 867/4101 /  23 août 2019',
 'Réf. : C83/0422 /  23 août 2019',
 'Réf. : C82/0274 /  23 août 2019',
 'Réf. : 974/9070 /  23 août 2019',
 'Réf. : C84/0259 /  23 août 2019',
 'Réf. : C73/1443 /  23 août 2019',
 'Réf. : B74/0797 /  23 août 2019',
 'Réf. : B05/1484 /  23 août 2019',
 'Réf. : B78/1012 /  23 août 2019',
 'Réf. : 953/A755 /  23 août 2019',
 'Réf. : B74/1669 /  23 août 2019',
 'Réf. : C37/0246 /  23 août 2019',
 'Réf. : C75/1311 /  23 août 2019',
 'Réf. : C84/0366 /  23 août 2019',
 'Réf. : B85/1110 /  23 août 2019',
 'Réf. : C84/0554 /  23 août 2019',
 'Réf. : C82/0742 /  23 août 2019',
 'Réf. : C55/0478 /  23 août 2019',
 'Réf. : B70/0896 /  23 août 2019',
 'Réf. : C80/0207 /  23 août 2019',
 'Réf. : C80/0230 /  23 août 2019',
 'Réf. : C80/0232 /  23 août 2019',
 'Réf. : C76/0854 /  23 août 2019',
 'Réf. : C84/0406 /  23 août 2019',
 'Réf. : C84/0563 /  23 août 2019',
 'Réf. : C72/1154 /  23 août 2019',
 'Réf. : B80/1141 /  23 août 2019',
 'Réf. : C67/1454 /  23 août 2019',
 'Réf. : C84/0542 /  23 août 2019',
 'Réf. : C84/0034 /  23 août 2019',
 'Réf. : C84/0242 /  23 août 2019',
 'Réf. : C67/1452 /  23 août 2019',
 'Réf. : A96/1657 /  23 août 2019',
 'Réf. : C83/0040 /  23 août 2019',
 'Réf. : C61/1242 /  23 août 2019',
 'Réf. : C84/0401 /  23 août 2019',
 'Réf. : 735/4365 /  23 août 2019',
 'Réf. : C24/0915 /  23 août 2019',
 'Réf. : B96/0603 /  23 août 2019',
 'Réf. : A75/0326 /  23 août 2019',
 'Réf. : C56/1158 /  23 août 2019',
 'Réf. : C80/0505 /  23 août 2019',
 'Réf. : C76/1114 /  23 août 2019',
 'Réf. : C69/1457 /  23 août 2019',
 'Réf. : 991/32 /  23 août 2019',
 'Réf. : C77/1358 /  23 août 2019',
 'Réf. : A55/2111 /  23 août 2019',
 'Réf. : C74/1354 /  23 août 2019',
 'Réf. : C57/0127 /  23 août 2019',
 'Réf. : B74/1073 /  23 août 2019',
 'Réf. : B25/0893 /  23 août 2019',
 'Réf. : 924/B579 /  23 août 2019',
 'Réf. : B99/0586 /  23 août 2019',
 'Réf. : C75/0572 /  23 août 2019',
 'Réf. : C84/0520 /  23 août 2019',
 'Réf. : B66/0046 /  23 août 2019',
 'Réf. : C84/0515 /  23 août 2019',
 'Réf. : C84/0514 /  23 août 2019',
 'Réf. : B28/0353 /  23 août 2019',
 'Réf. : A38/0121 /  23 août 2019',
 'Réf. : C76/0298 /  23 août 2019',
 'Réf. : C58/1483 /  23 août 2019',
 'Réf. : 978/9996 /  23 août 2019',
 'Réf. : C77/1146 /  23 août 2019',
 'Réf. : C84/0500 /  23 août 2019',
 'Réf. : C84/0492 /  23 août 2019',
 'Réf. : C68/0532 /  23 août 2019',
 'Réf. : C83/0269 /  23 août 2019',
 'Réf. : C84/0386 /  23 août 2019',
 'Réf. : C32/0295 /  23 août 2019',
 'Réf. : C84/0387 /  23 août 2019',
 'Réf. : C83/0562 /  23 août 2019',
 'Réf. : C84/0488 /  23 août 2019',
 'Réf. : C37/0685 /  23 août 2019',
 'Réf. : C74/1154 /  23 août 2019',
 'Réf. : 925/B049 /  23 août 2019',
 'Réf. : C83/0360 /  23 août 2019',
 'Réf. : C82/0311 /  23 août 2019',
 'Réf. : 753/4285 /  23 août 2019',
 'Réf. : B59/1241 /  23 août 2019',
 'Réf. : C83/0208 /  23 août 2019',
 'Réf. : C81/0144 /  23 août 2019',
 'Réf. : A23/1034 /  23 août 2019',
 'Réf. : C82/0021 /  23 août 2019',
 'Réf. : C84/0213 /  23 août 2019',
 'Réf. : C01/0387 /  23 août 2019',
 'Réf. : C64/0344 /  23 août 2019',
 'Réf. : C84/0458 /  23 août 2019',
 'Réf. : C82/0636 /  23 août 2019',
 'Réf. : C84/0453 /  23 août 2019',
 'Réf. : C81/0089 /  23 août 2019',
 'Réf. : B60/0128 /  23 août 2019',
 'Réf. : C72/0545 /  23 août 2019',
 'Réf. : C16/0789 /  23 août 2019',
 'Réf. : C84/0416 /  23 août 2019',
 'Réf. : C84/0534 /  23 août 2019',
 'Réf. : 915/36 /  23 août 2019',
 'Réf. : C73/1581 /  23 août 2019',
 'Réf. : C79/1013 /  23 août 2019',
 'Réf. : C79/1012 /  23 août 2019',
 'Réf. : 803/9814 /  23 août 2019',
 'Réf. : B55/1284 /  23 août 2019',
 'Réf. : C83/0472 /  23 août 2019',
 'Réf. : A67/0159 /  23 août 2019',
 'Réf. : C81/0732 /  23 août 2019',
 'Réf. : C78/0133 /  23 août 2019',
 'Réf. : C84/0407 /  23 août 2019',
 'Réf. : C83/0253 /  23 août 2019',
 'Réf. : C83/0348 /  23 août 2019',
 'Réf. : C21/1642 /  23 août 2019',
 'Réf. : C84/0015 /  23 août 2019',
 'Réf. : B96/0521 /  23 août 2019',
 'Réf. : A18/1556 /  23 août 2019',
 'Réf. : A73/0604 /  23 août 2019',
 'Réf. : C68/1199 /  23 août 2019',
 'Réf. : A76/1067 /  23 août 2019',
 'Réf. : C84/0525 /  23 août 2019',
 'Réf. : B68/0074 /  23 août 2019',
 'Réf. : C74/1288 /  23 août 2019',
 'Réf. : C77/0020 /  23 août 2019',
 'Réf. : C84/0408 /  23 août 2019',
 'Réf. : B65/1903 /  23 août 2019',
 'Réf. : C84/0192 /  23 août 2019',
 'Réf. : A03/1977 /  23 août 2019',
 'Réf. : C63/1095 /  23 août 2019',
 'Réf. : B98/0023 /  23 août 2019',
 'Réf. : B43/0012 /  23 août 2019',
 'Réf. : C82/0685 /  23 août 2019',
 'Réf. : C83/0248 /  23 août 2019',
 'Réf. : C81/0007 /  23 août 2019',
 'Réf. : B80/1613 /  23 août 2019',
 'Réf. : B28/1282 /  23 août 2019',
 'Réf. : C80/0004 /  23 août 2019',
 'Réf. : C83/0246 /  23 août 2019',
 'Réf. : C83/0645 /  23 août 2019',
 'Réf. : C84/0002 /  23 août 2019',
 'Réf. : B76/1023 /  23 août 2019',
 'Réf. : C76/1376 /  23 août 2019',
 'Réf. : C69/1397 /  22 août 2019',
 'Réf. : A79/2064 /  22 août 2019',
 'Réf. : C83/0634 /  22 août 2019',
 'Réf. : 965/9937 /  22 août 2019',
 'Réf. : C83/0458 /  22 août 2019',
 'Réf. : C10/1555 /  22 août 2019',
 "Votre accès au site PAP.fr a été bloqué\r\n\t\tcar votre adresse IP présente les caractéristiques d'un robot.",
 'Réf. : C82/0263 /  22 août 2019',
 'Réf. : C01/1075 /  22 août 2019',
 'Réf. : B86/0267 /  22 août 2019',
 'Réf. : C73/0243 /  22 août 2019',
 'Réf. : C84/0334 /  22 août 2019',
 'Réf. : B78/0547 /  22 août 2019',
 'Réf. : C84/0329 /  22 août 2019',
 'Réf. : C83/0449 /  22 août 2019',
 'Réf. : A89/1316 /  22 août 2019',
 'Réf. : 961/B423 /  22 août 2019',
 'Réf. : B47/1363 /  22 août 2019',
 "Votre accès au site PAP.fr a été bloqué\r\n\t\tcar votre adresse IP présente les caractéristiques d'un robot.",
 'Réf. : B45/0552 /  22 août 2019',
 'Réf. : C80/0667 /  22 août 2019',
 'Réf. : C39/0466 /  22 août 2019']

In [196]:
loc_date=[]
for i in date:
    try:
        match=re.search(r'\/  \d\d\D*\d*', i).group(0)
    except:
        match='-1'
    loc_date.append(match)
loc_date=[i.strip('/  ') for i in loc_date]
loc_date

['27 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '27 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '23 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '-1',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019',
 '-1',
 '22 août 2019',
 '22 août 2019',
 '22 août 2019']

In [199]:
locations_data.Description.tolist()

['Station F. 2 min accès RER C, 900 m Tramway T3. 200 m station métro ligne 14 station BFM  et face MK2.  Orly à 20 min, Gare d\'Austerlitz et de Lyon à moins de 10 min.\n\r\nDans résidence neuve haut de gamme Vinci "Kalei", livraison 1ère quinzaine décembre, très beau studio au 11e et dernier étage, d\'une surface de 31\xa0m², orientation sud-ouest.\r\nTerrasse panoramique avec garde corps en verre, électricité et eau. Vue sur Tour Eiffel et Sacré Cœur.\n\r\nEntièrement meublé.\r\nPièce principale avec convertible et TV, cuisine Mobalpa ouverte avec plaque et hotte, four combiné micro ondes, réfrigérateur et mini lave vaisselle, porte à galandage pour la salle de bains avec douche, lave linge, placard, armoire, sèche serviettes.\n\r\nPrestations de qualité. Hauteur porte palière blindée 2.14 m, parquet massif, faïence sol et murs, double vitrage, volets motorisés.\n\r\nIdéal pour société et longue durée.\n\r\nLibre 1ère quinzaine décembre (infos promoteur).\r\nLoyer charges comprises (eau, électricité, internet inclus).',
 "F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartement d'une surface de 47 M² composé d'une entrée avec dressing , un double séjour avec porte vitrée (donnant la possibilité de créer une 2ème chambre) et beau parquet , une chambre avec un grand placard et parquet en bon état,  une salle de bains\r\net WC séparés.  Appartement lumineux bien que situé au 1er. étage dans un immeuble calme.\r\nProximité tous commerces et transports.\r\nLibre de suite .\r\nColocation acceptée.\n\r\nLoyer\xa0: 1.412,00 Euros charges comprises.",
 "Daumesnil. Haussmannien, au calme, 3 pièces, 53\xa0m², au 2e, meublé, belles prestations (moulures, cheminées, parquet), salle de bains marbre avec wc, cuisine équipée, salon, salle à manger, chambre, rangements.\r\nBail 1 an. Libre de suite.\r\nVisite jeudi 29, vendredi 30 et samedi 31 août de 13h à 18h avec possibilité pendant la matinée.\n\r\n(Agences s'abstenir).",
 "Immeuble année 2000, proche métro, bon standing, rue calme, au 4e ascenseur. Orientation Est. 2 pièces 57\xa0m², parquet, charme, lumineux\xa0: salon spacieux, chambre 12\xa0m², cuisine dinatoire équipée (réfrigérateur, four, lave-linge, plaque électrique), salle de bains (baignoire/douche), wc indépendants, rangements.\r\nTrès bon état. Chauffage électrique. Possibilité de parking.\r\nA meubler sur demande du locataire.\n\r\n1.950€/mois charge comprises\r\nAgences s'abstenir",
 'Métro et tramway T3 Porte de Bagnolet à 5 min. Studio 20 m², meublé.\n\r\nAu 1er étage, ascenseur, standing, très sécurisé avec 3 portes digicodes et interphone. Très calme, clair, sans vis-à-vis, donnant sur un petit jardin privatif.\n\r\nAvec\xa0: grande salle de bains/wc, coin cuisine équipé (réfrigérateur, four, micro-ondes, grill, lave-linge, aspirateur, éléments, table de travail), grande armoire, prise téléphonique.\n\r\nProche commerces et place Gambetta.\n\r\nGaranties et caution demandées.\n\r\nLoyer\xa0: 720 €/mois + 40 € charges.\n\r\nDisponible de suite.',
 "Grand Studio (F1) au cœur de Paris. Situé au 3ème étage donnant sur rue, l'appartement a été refait à neuf.  Lumineux, il se compose d'une petite entrée qui dessert une cuisine et la salle de douche - wc, et d'une grande pièce.\r\nL'appartement est disponible immédiatement.\r\nCaution demandée.\n\r\nLoyer\xa0: 900\xa0€ + charges 90\xa0€",
 'Studio 16m2 Refait à neuf\r\n23 Rue Pascal au bas de la rue Mouffetard\r\nEt de ses commerces\r\nLoyer Meublé\xa0: 820€ CC\n\n\r\n3ème étage, immeuble récent avec ascenseur.\r\nOrientation Ouest.\r\nExcellent état. Refait à neuf.\r\n1 pièce Sol parquet, Baie vitrée double vitrage et rideaux, Volet électrique.\r\n1 salle de bain avec wc et Douche et rangements, 1 Kitchenette équipée de Plaques électriques et Micro Onde Grill, Hotte et Réfrigérateur, Carrelage au sol.\r\nTrès fonctionnel.\r\nEau chaude inclus dans les charges, Chauffage électrique.\n\r\nDPE\xa0: D, GES\xa0: C.\n\r\nLoyer meublé\xa0: 820€ Charges comprises.\n\r\nM° Censier Daubenton ou Gobelins\r\nBus N°21, 27, 47, 83, 91 et Noctiliens,\r\nVelib.\n\r\nMoins de 10mn à pied ou en Bus ou en Vélib, des lycées Saint Louis, Louis Le Grand et Henri IV, ENS Ulm, Mines Paris, CNRS Pierre et Marie Curie, ESPCI (5mn), UPMC Jussieu, Agro Paritech (4mn).\r\nEntre 12 et 15mn à pied ou en Bus de la PAES UPMC (CHU Pitié Salpêtrière), Sorbonne ou Collège de France.\r\nCommerces de proximité, Picard, marché et Drive piéton Carrefour (à 20mètres), Monoprix.\n\r\nEngagement de caution demandé.\n\r\nLoyer\xa0: 820\xa0€ charges comprises',
 "Près rue mouffetard, au fond d'un grand jardin fruitier, dans petit immeuble de 2 étages, magnifique studio meublé, équipé, 30\xa0m² avec grande mezzanine, poutres anciennes apparentes.\r\nJardin partagé, chaque appartement utilise une partie.\n\r\nCuisine marbre équipée, lave-linge, machine à café, four micro-ondes, vaisselle et couverts, salle de bain marbre, baignoire, serviettes de bains, lit double king-size avec linge, table, 5 chaises, bureau, petites tables, canapé confortable, TV internet contrat orange compris dans le loyer.\n\r\nAtmosphère conviviale dans toute la maison.\n\r\nLoyer\xa0: 1.200\xa0€/mois charges comprises (sauf électricité et gaz).\n\r\nLibre de suite\n\r\nPossibilité courte durée.",
 'Beau studio, 30 m², rez-de-chaussée sur cour, au calme.\r\nPrès du métro et bus, commerces à proximité.\r\nDigicode et gardien.\r\nRefait à neuf, salle de bains et wc séparés, cuisine équipée avec équipement neuf (four micro-ondes combiné, plaque de cuisson, réfrigérateur neuf, lave-linge).\r\n+ cave.\n\r\nChauffage collectif.\n\r\nLoyer charges comprises.',
 'Paris (75016). Pour étudiant(e)s.\n\r\nStudette 11 m² refaite à neuf, dans bel immeuble Haussmannien, gardien digicode, au 7ème étage sans ascenseur.\n\r\nProche Jean-Baptiste Say - Molière, tous commerces et transports (métros lignes 9 et 10, bus 22, 52, 72).\n\r\nCalme, meublée\xa0: douche, cuisinette (plaques, micro-ondes et réfrigérateur), mezzanine avec lit, wifi, chauffage collectif, wc sur palier.\n\r\nCaution et garanties demandées. Eligible APL.\n\r\nLoyer\xa0: 540\xa0€/mois charges comprises (eau, chauffage WIFI, électricité).',
 'Station F. 2 min accès RER C, 900 m Tramway T3. 200 m station métro ligne 14 station BFM  et face MK2.  Orly à 20 min, Gare d\'Austerlitz et de Lyon à moins de 10 min.\n\r\nDans résidence neuve haut de gamme Vinci "Kalei", livraison 1ère quinzaine décembre, très beau studio au 11e et dernier étage, d\'une surface de 31\xa0m², orientation sud-ouest.\r\nTerrasse panoramique avec garde corps en verre, électricité et eau. Vue sur Tour Eiffel et Sacré Cœur.\n\r\nEntièrement meublé.\r\nPièce principale avec convertible et TV, cuisine Mobalpa ouverte avec plaque et hotte, four combiné micro ondes, réfrigérateur et mini lave vaisselle, porte à galandage pour la salle de bains avec douche, lave linge, placard, armoire, sèche serviettes.\n\r\nPrestations de qualité. Hauteur porte palière blindée 2.14 m, parquet massif, faïence sol et murs, double vitrage, volets motorisés.\n\r\nIdéal pour société et longue durée.\n\r\nLibre 1ère quinzaine décembre (infos promoteur).\r\nLoyer charges comprises (eau, électricité, internet inclus).',
 "F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartement d'une surface de 47 M² composé d'une entrée avec dressing , un double séjour avec porte vitrée (donnant la possibilité de créer une 2ème chambre) et beau parquet , une chambre avec un grand placard et parquet en bon état,  une salle de bains\r\net WC séparés.  Appartement lumineux bien que situé au 1er. étage dans un immeuble calme.\r\nProximité tous commerces et transports.\r\nLibre de suite .\r\nColocation acceptée.\n\r\nLoyer\xa0: 1.412,00 Euros charges comprises.",
 "Daumesnil. Haussmannien, au calme, 3 pièces, 53\xa0m², au 2e, meublé, belles prestations (moulures, cheminées, parquet), salle de bains marbre avec wc, cuisine équipée, salon, salle à manger, chambre, rangements.\r\nBail 1 an. Libre de suite.\r\nVisite jeudi 29, vendredi 30 et samedi 31 août de 13h à 18h avec possibilité pendant la matinée.\n\r\n(Agences s'abstenir).",
 "Immeuble année 2000, proche métro, bon standing, rue calme, au 4e ascenseur. Orientation Est. 2 pièces 57\xa0m², parquet, charme, lumineux\xa0: salon spacieux, chambre 12\xa0m², cuisine dinatoire équipée (réfrigérateur, four, lave-linge, plaque électrique), salle de bains (baignoire/douche), wc indépendants, rangements.\r\nTrès bon état. Chauffage électrique. Possibilité de parking.\r\nA meubler sur demande du locataire.\n\r\n1.950€/mois charge comprises\r\nAgences s'abstenir",
 'Métro et tramway T3 Porte de Bagnolet à 5 min. Studio 20 m², meublé.\n\r\nAu 1er étage, ascenseur, standing, très sécurisé avec 3 portes digicodes et interphone. Très calme, clair, sans vis-à-vis, donnant sur un petit jardin privatif.\n\r\nAvec\xa0: grande salle de bains/wc, coin cuisine équipé (réfrigérateur, four, micro-ondes, grill, lave-linge, aspirateur, éléments, table de travail), grande armoire, prise téléphonique.\n\r\nProche commerces et place Gambetta.\n\r\nGaranties et caution demandées.\n\r\nLoyer\xa0: 720 €/mois + 40 € charges.\n\r\nDisponible de suite.',
 "Grand Studio (F1) au cœur de Paris. Situé au 3ème étage donnant sur rue, l'appartement a été refait à neuf.  Lumineux, il se compose d'une petite entrée qui dessert une cuisine et la salle de douche - wc, et d'une grande pièce.\r\nL'appartement est disponible immédiatement.\r\nCaution demandée.\n\r\nLoyer\xa0: 900\xa0€ + charges 90\xa0€",
 'Studio 16m2 Refait à neuf\r\n23 Rue Pascal au bas de la rue Mouffetard\r\nEt de ses commerces\r\nLoyer Meublé\xa0: 820€ CC\n\n\r\n3ème étage, immeuble récent avec ascenseur.\r\nOrientation Ouest.\r\nExcellent état. Refait à neuf.\r\n1 pièce Sol parquet, Baie vitrée double vitrage et rideaux, Volet électrique.\r\n1 salle de bain avec wc et Douche et rangements, 1 Kitchenette équipée de Plaques électriques et Micro Onde Grill, Hotte et Réfrigérateur, Carrelage au sol.\r\nTrès fonctionnel.\r\nEau chaude inclus dans les charges, Chauffage électrique.\n\r\nDPE\xa0: D, GES\xa0: C.\n\r\nLoyer meublé\xa0: 820€ Charges comprises.\n\r\nM° Censier Daubenton ou Gobelins\r\nBus N°21, 27, 47, 83, 91 et Noctiliens,\r\nVelib.\n\r\nMoins de 10mn à pied ou en Bus ou en Vélib, des lycées Saint Louis, Louis Le Grand et Henri IV, ENS Ulm, Mines Paris, CNRS Pierre et Marie Curie, ESPCI (5mn), UPMC Jussieu, Agro Paritech (4mn).\r\nEntre 12 et 15mn à pied ou en Bus de la PAES UPMC (CHU Pitié Salpêtrière), Sorbonne ou Collège de France.\r\nCommerces de proximité, Picard, marché et Drive piéton Carrefour (à 20mètres), Monoprix.\n\r\nEngagement de caution demandé.\n\r\nLoyer\xa0: 820\xa0€ charges comprises',
 "Près rue mouffetard, au fond d'un grand jardin fruitier, dans petit immeuble de 2 étages, magnifique studio meublé, équipé, 30\xa0m² avec grande mezzanine, poutres anciennes apparentes.\r\nJardin partagé, chaque appartement utilise une partie.\n\r\nCuisine marbre équipée, lave-linge, machine à café, four micro-ondes, vaisselle et couverts, salle de bain marbre, baignoire, serviettes de bains, lit double king-size avec linge, table, 5 chaises, bureau, petites tables, canapé confortable, TV internet contrat orange compris dans le loyer.\n\r\nAtmosphère conviviale dans toute la maison.\n\r\nLoyer\xa0: 1.200\xa0€/mois charges comprises (sauf électricité et gaz).\n\r\nLibre de suite\n\r\nPossibilité courte durée.",
 'Beau studio, 30 m², rez-de-chaussée sur cour, au calme.\r\nPrès du métro et bus, commerces à proximité.\r\nDigicode et gardien.\r\nRefait à neuf, salle de bains et wc séparés, cuisine équipée avec équipement neuf (four micro-ondes combiné, plaque de cuisson, réfrigérateur neuf, lave-linge).\r\n+ cave.\n\r\nChauffage collectif.\n\r\nLoyer charges comprises.',
 'Paris (75016). Pour étudiant(e)s.\n\r\nStudette 11 m² refaite à neuf, dans bel immeuble Haussmannien, gardien digicode, au 7ème étage sans ascenseur.\n\r\nProche Jean-Baptiste Say - Molière, tous commerces et transports (métros lignes 9 et 10, bus 22, 52, 72).\n\r\nCalme, meublée\xa0: douche, cuisinette (plaques, micro-ondes et réfrigérateur), mezzanine avec lit, wifi, chauffage collectif, wc sur palier.\n\r\nCaution et garanties demandées. Eligible APL.\n\r\nLoyer\xa0: 540\xa0€/mois charges comprises (eau, chauffage WIFI, électricité).',
 "Dans copropriété calme et bien entretenue, studio de 21,5m2 loué meublé avec coin cuisine équipé (plaque, micro-ondes,  réfrigérateur), lave-linge, canapé-lit Maison du Convertible (vrai matelas), rangements, salle d'eau (douche, wc), cave, visiophone.\r\nEntièrement refait à neuf, fenêtres en double vitrage. Au 1er étage sur cour.\r\nEau chaude et chauffage individuels électriques à la charge du locataire.\n\r\nSitué au pied du métro Marcadet-Poissonniers (lignes 4 et 12).\n\r\nDisponible début septembre. Caution solidaire demandée.\r\nDépôt de garantie\xa0: 1560€.\r\nLoyer\xa0: 780 €/mois dont provision charges mensuelles\xa0: 60€.\n\r\nVisites dimanche 25/08 ou samedi 31/08. Créneaux de visite à réserver par mail.",
 "Bail meublé code civil (société ou hab.secondaire) exclusivement. Durée ferme mini\xa06 mois, 1 an souhaité.\n\r\n(Triangle Vendôme / Opéra /Louvre). T3, 74 m²- , 3ème- Séjour, 2 chambres spacieuses, kitchen. équipée, bains marbre +sanitaires  qualité + wc + autre wc séparés, nombreux vitraux, meubles style parisien.\r\n(Abonnements Électricité,/gaz)\r\n(internet /cable non compris)\n\r\nConditions contractuelles à charge du preneur :\r\n - Taxes d'habitation  (2.535€) et d'ordure ménagère (320€)\r\n- Entretien . annuel  chaud. gaz (130€)\r\n- Restitution linge maison\xa0après nettoyage par professionnel\r\n- Ménage final de sortie soigné requis (vitres, lustres, volets inclus).\n\r\nLibre au 8 avril 2019\r\n2 mois de garantie\r\nGarantie bancaire ou paiement d'avance totalité loyers + 2 mois DG\n\r\nParis (first arrondissement) nearby Vendôme - Opéra - Tuileries - 3 room fully furbished apartement (Parisian-style furniture and decoration) - - Classic 1830 building - 3d-  - 3  points lock gateway - 74 sq.m (800 sq/ ft)- 1 living/dining room - 2 large bedrooms - (2 hight wind/room) -equipped kitchen - big bathroom marble with classic clawfoot tub and toilet - separate W.C.- marble fireplaces - moldings - stained glasses windows in livingroom, bathroom and kitchen -\r\n(Electricity, gaz, d'habitation tax and taxes of household waste non included)\r\nAnnual maintenance of the gaz boiler required.\r\nFinal house linen cleaning out and ironing in laundry required for bed sheets,pillow cases and toilet towels -\r\nFinal soigné output household also required (chandeliers, windows and shutters included)\r\nAvailable april 8th2019\r\nLoyer\xa0: 2370\xa0€ charges comprises",
 '\n\t\t\t\t\tMETRO DUPLEIX - STUDIO SUR JARDIN PRIVE TERRASSE\t\t\t\t',
 "T2 meublé de 42 m², au 90 boulevard de Grenelle, entre métros Dupleix et Motte Picquet.\n\r\nRefait à neuf Au 1er étage sans ascenseur.\r\nEntrée avec dressing, cuisine américaine équipée (lave-linge, lave-vaisselle, micro-ondes, sèche-linge, réfrigérateur/congélateur), chambre sur cour avec nombreux rangements, salle d'eau avec grand bac de douche et toilettes séparés. Double vitrage. Chauffage individuel gaz.\n\r\nLoyer\xa0: 1700\xa0€/mois charges comprises.\r\nLibre: 2 septembre 2019.",
 "Métro La Muette. Rue des Vignes. Au 3e étage, ascenseur. Pas de colocation.\r\nGrand studio traversant de 31 m², sans vis-à-vis, entièrement meublé, comprenant\xa0: petite salle à manger, chambre avec placards / penderie, salle de bains avec baignoire d'angle, cuisine agencée avec de nombreux rangements, lave-linge séchant, lave-vaisselle, four, micro-ondes, plaques vitrocéramique, hotte, réfrigérateur/congélateur, téléviseur écran plat.\r\nDigicode + interphone. Eau chaude et chauffage collectifs.\n\r\n Libre de suite. 1.295.00 €/mois charges comprises.\r\nPrévoir dossier pour rendez-vous . Visites après 19h00 .",
 'Entrée Parc Buttes Chaumont. Avenue Maturin Moreau.\n\r\nImmeuble de standing moderne ravalé, au 2e étage avec ascenseur, grand 2 pièces 51\xa0m² environ entièrement refait à neuf\xa0: entrée, cuisine, salle de bains, wc séparés, nombreux placards, loggia. Calme et ensoleillé. Cave. Métros et nombreux bus à proximité.\n\r\nLibre de suite.\n\r\nSe présenter avec dossier.\n\r\nLoyer\xa0: 1.360\xa0€/mois + 140\xa0€ provision charges (eau chaude et chauffage central inclus).',
 'Métro Passy. Agréable studio environ 23 m², au 3ème étage, très calme, ensoleillé, deux grandes fenêtres double vitrage oscillo-battant.  Petite entrée, salle de bains avec douche, lavabo, wc, eau chaude individuelle, chauffage. Pièce principale avec placard penderie et meuble, télévision HD, table, assises... Cuisine équipée\xa0: plaque, frigo, micro-ondes, placards.. Situé  au coeur de Paris , dans un quartier calme,  avec tous commerces, à proximité de la Tour Eiffel, Trocadéro . Convient bien aux étudiants.\n\n\r\nLoyer\xa0: 1190\xa0€ charges comprises\r\nLoyer\xa0: 1190\xa0€ charges comprises',
 "Charmant studio meublé de 14 m² (pour une personne), très bien situé face à l'arrêt du T3 'Porte de Vanves' et du métro ligne 13.\n\r\nAu 5ème étage avec ascenseur, vue dégagée sur cour, très calme.\r\nRésidence bien tenue avec gardien, digicode, câblée avec 4G.\n\r\nStudio refait à neuf avec literie de qualité, vaisselle, cuisinette équipée de tous les appareils électriques (y compris réfrigérateur-congélateur neuf), à l'exception du four.\r\nLocation à l'année.\n\r\nSalle d'eau indépendante avec fenêtre\xa0: vaste douche, wc et lavabo. Cumulus de 30L neuf. Chauffage central collectif par radiateur (diagnostic énergétique établi par défaut).\n\r\nDoubles vitrages avec rideau occultant.\n\r\nSituation exceptionnelle dans un quartier vivant avec tous les commerces à proximité.\n\r\nVisitable dès le 27 août sur rendez-vous et louable de suite.\n\r\nLoyer\xa0: 620 €/mois + charges de 80\xa0€ (eau, chauffage collectif, ascenseur, poubelles, concierge, nettoyage des parties communes..). L'électricité est en sus (compteur individuel).",

In [203]:
price=pd.DataFrame(price_list)
localisation=pd.DataFrame(location)
surface=pd.DataFrame(m2)
type_appart=pd.DataFrame(loc_type)
date=pd.DataFrame(loc_date)
location_data=pd.concat([type_appart,surface,price,localisation,date,descriptions], axis=1)
location_data.columns=['Type_appart','Surface m²','Price €','Localisation','Date Post','Description']
location_data

,Type_appart,Surface m²,Price €,Localisation,Date Post,Description
0,meublee studio,31m,1.390,Paris 13E,27 août 2019,"Station F. 2 min accès RER C, 900 m Tramway T3..."
1,appartement,47m,1.412,Paris 20E,23 août 2019,F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartem...
2,meublee appartement,53m,1.533,Paris,23 août 2019,"Daumesnil. Haussmannien, au calme, 3 pièces, 5..."
3,appartement,57m,1.950,Paris 11,23 août 2019,"Immeuble année 2000, proche métro, bon standin..."
4,meublee studio,20m,760,Paris 20E,23 août 2019,Métro et tramway T3 Porte de Bagnolet à 5 min....
5,appartement,-1,990,Paris 1Er,23 août 2019,Grand Studio (F1) au cœur de Paris. Situé au 3...
6,meublee studio,16m,820,Paris,23 août 2019,Studio 16m2 Refait à neuf\r\n23 Rue Pascal au ...
7,meublee studio,30m,1.200,Paris 13E,23 août 2019,"Près rue mouffetard, au fond d'un grand jardin..."
8,meublee studio,30m,1.185,Paris 15E,23 août 2019,"Beau studio, 30 m², rez-de-chaussée sur cour, ..."
9,meublee studio,11m,540,Paris 16E,23 août 2019,Paris (75016). Pour étudiant(e)s.\n\r\nStudett...
10,meublee studio,31m,1.390,Paris 13E,27 août 2019,"Station F. 2 min accès RER C, 900 m Tramway T3..."
11,appartement,47m,1.412,Paris 20E,23 août 2019,F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartem...
12,meublee appartement,53m,1.533,Paris,23 août 2019,"Daumesnil. Haussmannien, au calme, 3 pièces, 5..."
13,appartement,57m,1.950,Paris 11,23 août 2019,"Immeuble année 2000, proche métro, bon standin..."
14,meublee studio,20m,760,Paris 20E,23 août 2019,Métro et tramway T3 Porte de Bagnolet à 5 min....
15,appartement,-1,990,Paris 1Er,23 août 2019,Grand Studio (F1) au cœur de Paris. Situé au 3...
16,meublee studio,16m,820,Paris,23 août 2019,Studio 16m2 Refait à neuf\r\n23 Rue Pascal au ...
17,meublee studio,30m,1.200,Paris 13E,23 août 2019,"Près rue mouffetard, au fond d'un grand jardin..."
18,meublee studio,30m,1.185,Paris 15E,23 août 2019,"Beau studio, 30 m², rez-de-chaussée sur cour, ..."
19,meublee studio,11m,540,Paris 16E,23 août 2019,Paris (75016). Pour étudiant(e)s.\n\r\nStudett...
20,meublee studio,21m,780,Paris 18E,23 août 2019,"Dans copropriété calme et bien entretenue, stu..."
21,meublee appartement,74m,2.370,Paris,23 août 2019,Bail meublé code civil (société ou hab.seconda...
22,meublee studio,25m,1.350,Paris 15E,23 août 2019,\n\t\t\t\t\tMETRO DUPLEIX - STUDIO SUR JARDIN ...
23,meublee appartement,42m,1.700,Paris 15E,23 août 2019,"T2 meublé de 42 m², au 90 boulevard de Grenell..."
24,meublee appartement,31m,1.295,Paris 16E,23 août 2019,"Métro La Muette. Rue des Vignes. Au 3e étage, ..."
25,appartement,51m,1.500,Paris 19E,23 août 2019,Entrée Parc Buttes Chaumont. Avenue Maturin Mo...
26,meublee appartement,23m,1.190,Paris 16E,23 août 2019,"Métro Passy. Agréable studio environ 23 m², au..."
27,meublee studio,14m,700,Paris 14E,23 août 2019,Charmant studio meublé de 14 m² (pour une pers...
28,meublee studio,12m,699,Paris 8E,23 août 2019,Champs-Élysées.\r\nStudette exposé Sud-Ouest -...
29,meublee chambre,13m,650,Paris 11E,23 août 2019,Chambre meublée pour étudiant au 6ème étage sa...
...,...,...,...,...,...,...
170,meublee studio,18m,1.080,Paris 16E,23 août 2019,Studio meublé tout confort dans bel immeuble a...
171,meublee appartement,51m,1.685,Paris 11E,23 août 2019,Appartement meublé récemment rénové à louer.\n...
172,meublee studio,27m,1.150,Paris 17E,23 août 2019,"Situé dans un quartier recherché, au pied du m..."
173,appartement,46m,1.450,Paris 14E,23 août 2019,"Appartement à 300 mètres du métro Alésia, supe..."
174,meublee appartement,38m,1.600,Paris 17E,23 août 2019,Location appartement 38 m² : 1 séjour et chamb...
175,meublee studio,36m,1.100,Paris 8E,23 août 2019,"Meublée 1 an minimum, avenue Wagram (8ème Pari..."
176,meublee chambre,10m,530,Paris 16E,23 août 2019,1 pièce 1 chambre 10 m²\r\nChambre meublée d...
177,meublee appartement,70m,2.500,Paris 16E,23 août 2019,"Appartement 70 m², immeuble haussmannien, 3e ..."
178,meublee appartement,50m,1.950,Paris 3E,22 août 2019,"Proche Beaubourg, métro Rambuteau.\n\r\n1er ét..."
179,meublee studio,48m,1.800,Paris 17E,22 août 2019,Large studio avec terrasse - entièrement rénov...
180,appartement,59m,2.400,Paris 2E,22 août 2019,"Très bel appartement de grand standing, situé ..."
181,meublee appartement,50m,2.390,Paris,22 août 2019,Superbe 2 pièces 50 m². Rue St-Paul. Ascenseur...
182,meublee studio,21m,1.030,Paris 16E,22 août 2019,"Rue Greuze. Immeuble Haussmannien, de grand st..."
183,studio,16m,820,Paris 17E,22 août 2019,Monceau ou Malesherbes.\r\nImmeuble de très bo...
184,Accès bloque,-1,-1,-1,-1,"Pour obtenir le déblocage de votre accès, veui..."
185,appartement,75m,2.450,Paris 11E,22 août 2019,"Côté Marais / Place des Vosges,\r\ndans réside..."
186,meublee studio,29m,1.300,Paris 12E,22 août 2019,Confortable studio meublé refait à neuf par un...
187,meublee studio,14m,800,Paris 18E,22 août 2019,"Propose en bail mobilité, agréable studio meub..."
188,appartement,52m,2.400,Paris 6E,22 août 2019,"Rue des Beaux-Arts, au coeur du quartier Saint..."
189,meublee studio,25m,809,Paris 12E,22 août 2019,PARIS 75012 Studio meublé de 25 m² refait à ne...
190,meublee studio,35m,1.100,Paris 14E,22 août 2019,Studio de 35 m² meublé et équipé a louer penda...
191,meublee studio,10m,550,Paris 13E,22 août 2019,A louer à compter du 1er septembre une studett...
192,appartement,33m,1.100,Paris 18E,22 août 2019,Deux pièces double exposition.\n\r\nEntrée ave...
193,meublee appartement,62m,2.115,Paris 15E,22 août 2019,\n\t\t\t\t\tBeau 3 pièces meublé\t\t\t\t
194,meublee studio,14m,850,Paris,22 août 2019,Au cœur du marché de Levis (46 rue de Levis). ...
195,appartement,30m,1.120,Paris 15E,22 août 2019,"Paris 15e.\n\r\nMetro Vaugirard/Commerce, derr..."
196,Accès bloque,-1,-1,-1,-1,"Pour obtenir le déblocage de votre accès, veui..."
197,meublee appartement,47m,1.599,Paris 15E,22 août 2019,"Appartement meublé, quartier calme, bel immeub..."
198,meublee appartement,65m,2.450,Paris 18E,22 août 2019,3/4 pièces. Appartement meublé 65 m² sans vis-...
199,meublee appartement,38m,1.650,Paris 4E,22 août 2019,Appartement meublé de 35 m² au deuxième étage ...

In [204]:
location_data.drop_duplicates()

,Type_appart,Surface m²,Price €,Localisation,Date Post,Description
0,meublee studio,31m,1.390,Paris 13E,27 août 2019,"Station F. 2 min accès RER C, 900 m Tramway T3..."
1,appartement,47m,1.412,Paris 20E,23 août 2019,F2/F3 Métro Gambetta PARIS 75020\n\r\nAppartem...
2,meublee appartement,53m,1.533,Paris,23 août 2019,"Daumesnil. Haussmannien, au calme, 3 pièces, 5..."
3,appartement,57m,1.950,Paris 11,23 août 2019,"Immeuble année 2000, proche métro, bon standin..."
4,meublee studio,20m,760,Paris 20E,23 août 2019,Métro et tramway T3 Porte de Bagnolet à 5 min....
5,appartement,-1,990,Paris 1Er,23 août 2019,Grand Studio (F1) au cœur de Paris. Situé au 3...
6,meublee studio,16m,820,Paris,23 août 2019,Studio 16m2 Refait à neuf\r\n23 Rue Pascal au ...
7,meublee studio,30m,1.200,Paris 13E,23 août 2019,"Près rue mouffetard, au fond d'un grand jardin..."
8,meublee studio,30m,1.185,Paris 15E,23 août 2019,"Beau studio, 30 m², rez-de-chaussée sur cour, ..."
9,meublee studio,11m,540,Paris 16E,23 août 2019,Paris (75016). Pour étudiant(e)s.\n\r\nStudett...
20,meublee studio,21m,780,Paris 18E,23 août 2019,"Dans copropriété calme et bien entretenue, stu..."
21,meublee appartement,74m,2.370,Paris,23 août 2019,Bail meublé code civil (société ou hab.seconda...
22,meublee studio,25m,1.350,Paris 15E,23 août 2019,\n\t\t\t\t\tMETRO DUPLEIX - STUDIO SUR JARDIN ...
23,meublee appartement,42m,1.700,Paris 15E,23 août 2019,"T2 meublé de 42 m², au 90 boulevard de Grenell..."
24,meublee appartement,31m,1.295,Paris 16E,23 août 2019,"Métro La Muette. Rue des Vignes. Au 3e étage, ..."
25,appartement,51m,1.500,Paris 19E,23 août 2019,Entrée Parc Buttes Chaumont. Avenue Maturin Mo...
26,meublee appartement,23m,1.190,Paris 16E,23 août 2019,"Métro Passy. Agréable studio environ 23 m², au..."
27,meublee studio,14m,700,Paris 14E,23 août 2019,Charmant studio meublé de 14 m² (pour une pers...
28,meublee studio,12m,699,Paris 8E,23 août 2019,Champs-Élysées.\r\nStudette exposé Sud-Ouest -...
29,meublee chambre,13m,650,Paris 11E,23 août 2019,Chambre meublée pour étudiant au 6ème étage sa...
30,meublee studio,26m,1.280,Paris 5E,23 août 2019,"Panthéon, Près Mouffetard et lycée Henri IV.\n..."
31,meublee studio,15m,690,Paris 20E,23 août 2019,Ce logement est entièrement rénové. Le studio ...
32,studio,12m,540,Paris 14E,23 août 2019,Métros Plaisance/Alésia. Studette 12 m² enviro...
33,meublee appartement,22m,850,Paris 18E,23 août 2019,"Cimetière Montmartre. T1 bon état, meublé, 22 ..."
34,appartement,32m,1.180,Paris 14E,23 août 2019,"2 pièces meublées de 31,07 m², (séjour : 11,50..."
35,meublee appartement,34m,1.290,Paris 13E,23 août 2019,"Dans bel immeuble haussmannien, 2 pièces, 34 m..."
36,meublee studio,19m,850,Paris 14E,23 août 2019,"Studio de 19m2, métro Alésia/Porte d'Orléans a..."
37,meublee studio,13m,500,Paris,23 août 2019,18e-studio meublé 13m2- près de la place de la...
38,meublee studio,15m,850,Paris 4E,23 août 2019,Au 22 rue des Rosiers. Au 6ème et dernier étag...
39,meublee studio,22m,1.200,Paris 18E,23 août 2019,Professeur - Conférencier (Grandes Ecoles) lo...
...,...,...,...,...,...,...
169,appartement,86m,2.500,Paris 16E,23 août 2019,"Rue Duret, métro Argentine/Victor Hugo, proxim..."
170,meublee studio,18m,1.080,Paris 16E,23 août 2019,Studio meublé tout confort dans bel immeuble a...
171,meublee appartement,51m,1.685,Paris 11E,23 août 2019,Appartement meublé récemment rénové à louer.\n...
172,meublee studio,27m,1.150,Paris 17E,23 août 2019,"Situé dans un quartier recherché, au pied du m..."
173,appartement,46m,1.450,Paris 14E,23 août 2019,"Appartement à 300 mètres du métro Alésia, supe..."
174,meublee appartement,38m,1.600,Paris 17E,23 août 2019,Location appartement 38 m² : 1 séjour et chamb...
175,meublee studio,36m,1.100,Paris 8E,23 août 2019,"Meublée 1 an minimum, avenue Wagram (8ème Pari..."
176,meublee chambre,10m,530,Paris 16E,23 août 2019,1 pièce 1 chambre 10 m²\r\nChambre meublée d...
177,meublee appartement,70m,2.500,Paris 16E,23 août 2019,"Appartement 70 m², immeuble haussmannien, 3e ..."
178,meublee appartement,50m,1.950,Paris 3E,22 août 2019,"Proche Beaubourg, métro Rambuteau.\n\r\n1er ét..."
179,meublee studio,48m,1.800,Paris 17E,22 août 2019,Large studio avec terrasse - entièrement rénov...
180,appartement,59m,2.400,Paris 2E,22 août 2019,"Très bel appartement de grand standing, situé ..."
181,meublee appartement,50m,2.390,Paris,22 août 2019,Superbe 2 pièces 50 m². Rue St-Paul. Ascenseur...
182,meublee studio,21m,1.030,Paris 16E,22 août 2019,"Rue Greuze. Immeuble Haussmannien, de grand st..."
183,studio,16m,820,Paris 17E,22 août 2019,Monceau ou Malesherbes.\r\nImmeuble de très bo...
184,Accès bloque,-1,-1,-1,-1,"Pour obtenir le déblocage de votre accès, veui..."
185,appartement,75m,2.450,Paris 11E,22 août 2019,"Côté Marais / Place des Vosges,\r\ndans réside..."
186,meublee studio,29m,1.300,Paris 12E,22 août 2019,Confortable studio meublé refait à neuf par un...
187,meublee studio,14m,800,Paris 18E,22 août 2019,"Propose en bail mobilité, agréable studio meub..."
188,appartement,52m,2.400,Paris 6E,22 août 2019,"Rue des Beaux-Arts, au coeur du quartier Saint..."
189,meublee studio,25m,809,Paris 12E,22 août 2019,PARIS 75012 Studio meublé de 25 m² refait à ne...
190,meublee studio,35m,1.100,Paris 14E,22 août 2019,Studio de 35 m² meublé et équipé a louer penda...
191,meublee studio,10m,550,Paris 13E,22 août 2019,A louer à compter du 1er septembre une studett...
192,appartement,33m,1.100,Paris 18E,22 août 2019,Deux pièces double exposition.\n\r\nEntrée ave...
193,meublee appartement,62m,2.115,Paris 15E,22 août 2019,\n\t\t\t\t\tBeau 3 pièces meublé\t\t\t\t
194,meublee studio,14m,850,Paris,22 août 2019,Au cœur du marché de Levis (46 rue de Levis). ...
195,appartement,30m,1.120,Paris 15E,22 août 2019,"Paris 15e.\n\r\nMetro Vaugirard/Commerce, derr..."
197,meublee appartement,47m,1.599,Paris 15E,22 août 2019,"Appartement meublé, quartier calme, bel immeub..."
198,meublee appartement,65m,2.450,Paris 18E,22 août 2019,3/4 pièces. Appartement meublé 65 m² sans vis-...
199,meublee appartement,38m,1.650,Paris 4E,22 août 2019,Appartement meublé de 35 m² au deuxième étage ...