In [1]:
import pandas as ps

In [2]:
df=ps.read_csv('GSAF5.csv', encoding='latin-1')
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Data columns (total 24 columns):
Case Number               5992 non-null object
Date                      5992 non-null object
Year                      5992 non-null int64
Type                      5992 non-null object
Country                   5949 non-null object
Area                      5590 non-null object
Location                  5496 non-null object
Activity                  5465 non-null object
Name                      5792 non-null object
Sex                       5425 non-null object
Age                       3311 non-null object
Injury                    5965 non-null object
Fatal (Y/N)               5973 non-null object
Time                      2779 non-null object
Species                   3058 non-null object
Investigator or Source    5977 non-null object
pdf                       5992 non-null object
href formula              5991 non-null object
href                      5989 non-null object
Case Number.1             5992 non-null object
Case Number.2             5992 non-null object
original order            5992 non-null int64
Unnamed: 22               1 non-null object
Unnamed: 23               2 non-null object
dtypes: int64(2), object(22)
memory usage: 1.1+ MB

In [4]:
df.isnull()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,True,True
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
8,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
9,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
11,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
14,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
15,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
16,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
17,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,True
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
24,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5963,False,False,False,False,False,True,True,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5964,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5965,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5966,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5967,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
5968,False,False,False,False,False,False,False,False,True,True,...,True,False,False,False,False,False,False,False,True,True
5969,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5970,False,False,False,False,False,True,True,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5971,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5972,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
5973,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5974,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5975,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5976,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5977,False,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,False,True,True
5978,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5979,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5980,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5981,False,False,False,False,False,True,True,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5982,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
5983,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5984,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5985,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5986,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
5987,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5988,False,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5989,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
5990,False,False,False,False,False,True,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
5991,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True

In [5]:
nul_col=df.isnull().sum()/df.shape[0]*100
nul_col=round(nul_col)
nul_col[nul_col>0]

Country          1.0
Area             7.0
Location         8.0
Activity         9.0
Name             3.0
Sex              9.0
Age             45.0
Time            54.0
Species         49.0
Unnamed: 22    100.0
Unnamed: 23    100.0
dtype: float64

calcultate nb of empty col in each col
select the solution:
    drop col with missing rate higher than certain predefined thresholds 
    interpolate (filling the missing values) data according to col nearby (country, area, name, type we can not interpolate; gender, age we could interpolate)
    null them 
    no more missing values

In [7]:
drop_col=nul_col[nul_col>70].index
df1=df.drop(drop_col,axis=1)
#either we put .index or we specify the columns, but in this case we have a condition so we put .index

In [8]:
df1.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [9]:
df1.shape

(5992, 22)

In [10]:
df1.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989

In [11]:
df1[['Case Number', 'Case Number.1', 'Case Number.2']].T.duplicated()
#if we put only one pair of brackets we'll get a serie not a dataframe

Case Number      False
Case Number.1    False
Case Number.2    False
dtype: bool

In [12]:
df1[['Case Number', 'Case Number.1', 'Case Number.2']].sample(int(df1.shape[0]*0.8)).T.duplicated()
#we select randomly % of rows

Case Number      False
Case Number.1    False
Case Number.2    False
dtype: bool

In [13]:
df1.Year.describe()

count    5992.000000
mean     1925.204606
std       286.473712
min         0.000000
25%      1942.000000
50%      1975.000000
75%      2003.000000
max      2016.000000
Name: Year, dtype: float64

In [14]:
df1.Year.value_counts()

2015    139
2011    128
2014    125
0       124
2013    122
2008    121
2009    120
2012    117
2007    112
2006    103
2016    103
2005    103
2010    101
2000     97
1959     93
1960     93
2001     92
2004     92
2003     92
2002     88
1962     86
1961     78
1995     76
1964     66
1998     65
1999     65
1996     61
1963     61
1966     58
1997     57
       ...
1785      1
1834      1
1791      1
1733      1
1721      1
1637      1
1617      1
77        1
5         1
1703      1
1755      1
1767      1
1771      1
1779      1
1787      1
1803      1
1749      1
1807      1
1811      1
1819      1
1805      1
1831      1
1555      1
1738      1
1859      1
1742      1
1758      1
1818      1
1822      1
1595      1
Name: Year, Length: 232, dtype: int64

In [15]:
sum(df1.Year<1200)
rows_to_drop=df1.Year[df1.Year<1200].index
df2=df1.drop(rows_to_drop)
df2.shape

(5865, 22)

In [16]:
df2.Date

0                      18-Sep-16
1                      18-Sep-16
2                      18-Sep-16
3                      17-Sep-16
4                      16-Sep-16
5                      15-Sep-16
6                      11-Sep-16
7                      07-Sep-16
8                      06-Sep-16
9                      05-Sep-16
10                     05-Sep-16
11                     04-Sep-16
12                     01-Sep-16
13                     29-Aug-16
14                     29-Aug-16
15                     27-Aug-16
16                     25-Aug-16
17                     07-Aug-16
18                     06-Aug-16
19                     04-Aug-16
20                     29-Jul-16
21                     28-Jul-16
22                     28-Jul-16
23                     27-Jul-16
24                     26-Jul-16
25                     24-Jul-16
26                     23-Jul-16
27                     23-Jul-16
28                     20-Jul-16
29                     17-Jul-16
                  ...
5835                 05-Jul-1787
5836        Reported 26-Sep-1785
5837                        1779
5838               Reported 1776
5839                        1776
5840        Reported 12-Jul-1771
5841                        1767
5842                        1764
5843                        1758
5844                        1749
5845                        1755
5846                        1748
5847                 17-Dec-1742
5848        Reported 06-Apr-1738
5849                        1733
5850                   June 1721
5851                 26-Mar-1703
5852                       1700s
5853                       1700s
5854                       1700s
5855    Late 1600s Reported 1728
5856               Reported 1638
5857               Reported 1637
5858               Reported 1617
5859                        1642
5860                        1595
5861    Letter dated 10-Jan-1580
5862                        1555
5863                    Ca. 1554
5864                    Ca. 1543
Name: Date, Length: 5865, dtype: object

In [17]:
df2[['Date','Year']].tail(20)

                          Date  Year
5845                      1755  1755
5846                      1748  1748
5847               17-Dec-1742  1742
5848      Reported 06-Apr-1738  1738
5849                      1733  1733
5850                 June 1721  1721
5851               26-Mar-1703  1703
5852                     1700s  1700
5853                     1700s  1700
5854                     1700s  1700
5855  Late 1600s Reported 1728  1642
5856             Reported 1638  1638
5857             Reported 1637  1637
5858             Reported 1617  1617
5859                      1642  1642
5860                      1595  1595
5861  Letter dated 10-Jan-1580  1580
5862                      1555  1555
5863                  Ca. 1554  1554
5864                  Ca. 1543  1543

In [18]:
df2.Date.sample(20)

4749    Reported 26-Sep-1932
4584    Reported 17-Jul-1938
4706               21-Aug-34
4208    Reported 02-Sep-1951
2668               15-Jun-84
1982                    1998
4917               08-Jul-26
443                16-Jun-13
447                06-Jun-13
3230               10-Oct-68
5647    Reported 11-Dec-1871
988                30-Aug-08
5182    Reported 26-Jun-1909
4752               10-Aug-32
1445               23-May-04
3700               25-Jan-61
739                01-Dec-10
3038               20-Jul-74
1024               21-Jun-08
2647               04-Nov-84
Name: Date, dtype: object

In [19]:
import re

In [26]:
def month_detection(value):
    months=['January', 'February', 'March', 'April', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    months_short=[i[:3] for i in months]
    value=str(value).strip()
    if re.fullmatch(r'[A-Za-z]{3,}',value):
        gr1=re.fullmatch(r'[A-Za-z]{3,}', value)
        if (gr1 in months )|(gr1 in months_short):
            return gr1
        else:
            return -1
    elif re.fullmatch(r'\d{4}', value):
        return -1
    elif re.fullmatch(r'[\'A-Za-z\.\(\)\?&]*', value):
        return -1
    elif re.fullmatch(r'\d{3,5}', value):
        return -1
    elif re.fullmatch(r'\d{2,4}s', value):
        return -1             
    elif re.fullmatch(r'\d{4}/\d{4}\)?', value):
        return -1 
    elif re.fullmatch(r'\d{4}\.\d{2}\.', value):
        return -1 
    elif re.fullmatch(r'([A-Za-z]+) \d+', value):
        gr1=re.fullmatch(r'([A-Za-z]+) \d+', value).group(1)
        if (gr1 in months )|(gr1 in months_short):
            return gr1
        else:
            return -1
    elif re.fullmatch(r'\d{1,2}-(\w{2,3})-\d{2,4}',value):
        return re.fullmatch(r'\d{1,2}-(\w{2,3})-\d{2,4}', value).group(1)
    elif re.fullmatch(r'Reported \d{1,2}-(\w{2,3})-\d{2,4}',value):
        return re.fullmatch(r'Reported \d{1,2}-(\w{2,3})-\d{2,4}', value).group(1)
    elif re.fullmatch(r'([A-Za-z]{3})-\d{2,4}',value):
        return re.fullmatch(r'([A-Za-z]{3})-\d{2,4}',value).group(1)
    else:
        return -1

In [27]:
month_detection('Feb-1542')

'Feb'

In [28]:
df2['Month']=df2.Date.apply(month_detection)
df2.Month.value_counts()
#we created a month column and we have applied the function month_detection defined

Jul        614
Aug        566
Sep        515
Jan        491
-1         484
Jun        470
Dec        416
Oct        407
Apr        400
Mar        391
Nov        388
May        363
Feb        353
Ap           2
October      1
Jut          1
30           1
June         1
26           1
Name: Month, dtype: int64

In [25]:
df2.Date.tolist()

['18-Sep-16',
 '18-Sep-16',
 '18-Sep-16',
 '17-Sep-16',
 '16-Sep-16',
 '15-Sep-16',
 '11-Sep-16',
 '07-Sep-16',
 '06-Sep-16',
 '05-Sep-16',
 '05-Sep-16',
 '04-Sep-16',
 '01-Sep-16',
 '29-Aug-16',
 '29-Aug-16',
 '27-Aug-16',
 '25-Aug-16',
 '07-Aug-16',
 '06-Aug-16',
 '04-Aug-16',
 '29-Jul-16',
 '28-Jul-16',
 '28-Jul-16',
 '27-Jul-16',
 '26-Jul-16',
 '24-Jul-16',
 '23-Jul-16',
 '23-Jul-16',
 '20-Jul-16',
 '17-Jul-16',
 '16-Jul-16',
 '16-Jul-16',
 '15-Jul-16',
 'Reported  14-Jul-2016',
 'Reported 08-Jul-2016',
 '08-Jul-16',
 '07-Jul-16',
 '07-Jul-16',
 '06-Jul-16',
 '04-Jul-16',
 '27-Jun-16',
 '25-Jun-16',
 '24-Jun-16',
 '23-Jun-16',
 '21-Jun-16',
 '21-Jun-16',
 '15-Jun-16',
 '15-Jun-16',
 '14-Jun-16',
 '11-Jun-16',
 '07-Jun-16',
 '05-Jun-16',
 '05-Jun-16',
 '04-Jun-16',
 '02-Jun-16',
 '02-Jun-16',
 '31-May-16',
 '29-May-16',
 '29-May-16',
 '22-May-16',
 '21-May-16',
 '21-May-16',
 '18-May-16',
 '15-May-16',
 '03-May-16',
 '02-May-16',
 '25-Apr-16',
 '23-Apr-16',
 '22-Apr-16',
 '19-Apr-16',
 '18-Apr-16',
 '13-Apr-16',
 '09-Apr-16',
 '08-Apr-16',
 '07-Apr-16',
 '07-Apr-16',
 '31-Mar-16',
 '30-Mar-16',
 '28-Mar-16',
 '28-Mar-16',
 '26-Mar-16',
 '13-Mar-16',
 '11-Mar-16',
 '10-Mar-16',
 '04-Mar-16',
 'Reported 03-Mar-2016',
 '02-Mar-16',
 '22-Feb-16',
 ' 19-Feb-2016',
 '12-Feb-16',
 'Reported 10-Feb-2016',
 '10-Feb-16',
 '05-Feb-16',
 '04-Feb-16',
 '29-Jan-16',
 '28-Jan-16',
 '25-Jan-16',
 '24-Jan-16',
 '24-Jan-16',
 '23-Jan-16',
 'Reported 11-Jan-2016',
 '05-Jan-16',
 '02-Jan-16',
 '26-Dec-15',
 '25-Dec-15',
 '22-Dec-15',
 '21-Dec-15',
 '21-Dec-15',
 '19-Dec-15',
 '13-Dec-15',
 '11-Dec-15',
 '08-Dec-15',
 '16-Nov-15',
 '15-Nov-15',
 '15-Nov-15',
 '10-Nov-15',
 '07-Nov-15',
 '03-Nov-15',
 '01-Nov-15',
 '01-Nov-15',
 '30-Oct-15',
 '28-Oct-15',
 '25-Oct-15',
 '21-Oct-15',
 '19-Oct-15',
 '17-Oct-15',
 '17-Oct-15',
 '17-Oct-15',
 '13-Oct-15',
 '09-Oct-15',
 '09-Oct-15',
 '08-Oct-15',
 '07-Oct-15',
 '05-Oct-15',
 '05-Oct-15',
 '04-Oct-15',
 '29-Sep-15',
 '26-Sep-15',
 '24-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '18-Sep-15',
 '17-Sep-15',
 '08-Sep-15',
 '06-Sep-15',
 '05-Sep-15',
 '04-Sep-15',
 '03-Sep-15',
 '01-Sep-15',
 'Sep-15',
 '29-Aug-15',
 '29-Aug-15',
 '22-Aug-15',
 '22-Aug-15',
 '20-Aug-15',
 '19-Aug-15',
 '18-Aug-15',
 '18-Aug-15',
 '10-Aug-15',
 '31-Jul-15',
 '26-Jul-15',
 '26-Jul-15',
 '25-Jul-15',
 '23-Jul-15',
 '23-Jul-15',
 '22-Jul-15',
 '19-Jul-15',
 '10-Jul-15',
 '08-Jul-15',
 '06-Jul-15',
 '04-Jul-15',
 '04-Jul-15',
 '03-Jul-15',
 '02-Jul-15',
 '01-Jul-15',
 '30-Jun-15',
 '30-Jun-15',
 '27-Jun-15',
 '27-Jun-15',
 '26-Jun-15',
 '26-Jun-15',
 '26-Jun-15',
 'Reported 25-Jun-2015',
 '25-Jun-15',
 '24-Jun-15',
 '24-Jun-15',
 '23-Jun-15',
 '19-Jun-15',
 '17-Jun-15',
 '14-Jun-15',
 '14-Jun-15',
 '13-Jun-15',
 '11-Jun-15',
 '07-Jun-15',
 '05-Jun-15',
 '01-Jun-15',
 '29-May-15',
 '29-May-15',
 '25-May-15',
 '24-May-15',
 '20-May-15',
 '15-May-15',
 '09-May-15',
 '07-May-15',
 '03-May-15',
 '02-May-15',
 '29-Apr-15',
 '26-Apr-15',
 '25-Apr-15',
 '24-Jun-15',
 '13-Apr-15',
 '11-Apr-15',
 '12-Apr-15',
 '31-Mar-15',
 '03-Apr-15',
 '29-Mar-15',
 '26-Mar-15',
 '21-Mar-15',
 '18-Mar-15',
 '16-Mar-15',
 '11-Mar-15',
 '10-Mar-15',
 '07-Mar-15',
 '15-Feb-15',
 '14-Feb-15',
 '09-Feb-15',
 '08-Feb-15',
 '05-Feb-15',
 '30-Jan-15',
 '27-Jan-15',
 '24-Jan-15',
 '19-Jan-15',
 '19-Jan-15',
 '17-Jan-15',
 '16-Jan-15',
 '08-Jan-15',
 '06-Jan-15',
 '03-Jan-15',
 '01-Jan-15',
 '29-Dec-14',
 '29-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 'Reported 23-Dec-2014',
 '15-Dec-14',
 'Reported 03-Dec-2014',
 '29-Nov-14',
 '20-Nov-14',
 '19-Nov-14',
 '16-Nov-14',
 'Reported 17-Nov-2014',
 '13-Nov-14',
 '10-Nov-14',
 '08-Nov-14',
 '31-Oct-14',
 '29-Oct-14',
 '22-Oct-14',
 '20-Oct-14',
 '19-Oct-14',
 '18-Oct-14',
 '17-Oct-14',
 '14-Oct-14',
 '12-Oct-14',
 '07-Oct-14',
 '11-Oct-14',
 '05-Oct-14',
 '05-Oct-14',
 '03-Oct-14',
 '03-Oct-14',
 '02-Oct-14',
 '02-Oct-14',
 '21-Sep-14',
 'Reported 12-Sep-2014',
 '13-Sep-14',
 '09-Sep-14',
 '06-Sep-14',
 '03-Sep-14',
 '02-Sep-14',
 'Sep-14',
 '31-Aug-14',
 '29-Aug-14',
 '29-Aug-14',
 '28-Aug-14',
 '27-Aug-14',
 '27-Aug-14',
 '27-Aug-14',
 'Reported 25-Aug-2014',
 '24-Aug-14',
 '16-Aug-14',
 '12-Aug-14',
 '10-Aug-14',
 '09-Aug-14',
 '09-Aug-14',
 '08-Aug-14',
 '06-Aug-14',
 '05-Aug-14',
 '02-Aug-14',
 '02-Aug-14',
 '01-Aug-14',
 'Aug-14',
 '27-Jul-14',
 '22-Jul-14',
 '21-Jul-14',
 '20-Jul-14',
 '16-Jul-14',
 '14-Jul-14',
 '13-Jul-14',
 '12-Jul-14',
 '09-Jul-14',
 '05-Jul-14',
 '05-Jul-14',
 '03-Jul-14',
 'Reported 27-Jun-2014',
 '25-Jun-14',
 '18-Jun-14',
 '18-Jun-14',
 'Reported 17-Jun-2014',
 '09-Jun-14',
 '09-Jun-14',
 '09-Jun-14',
 '08-Jun-14',
 '07-Jun-14',
 '01-Jun-14',
 '01-Jun-14',
 '01-Jun-14',
 '24-May-14',
 '23-May-14',
 '22-May-14',
 '20-Nov-15',
 '15-May-14',
 '14-May-14',
 '13-May-14',
 '11-May-14',
 'Reported 10-May-2014',
 '06-May-14',
 '01-May-14',
 '24-Apr-14',
 '22-Apr-14',
 '15-Apr-14',
 'Reported 12-Apr-2014',
 '12-Apr-14',
 '04-Apr-14',
 '04-Apr-14',
 '03-Apr-14',
 '29-Mar-14',
 '22-Mar-14',
 '22-Mar-14',
 '21-Mar-14',
 '18-Mar-14',
 '18-Mar-14',
 '13-Mar-14',
 '18-Mar-14',
 '12-Mar-14',
 '02-Mar-14',
 '20-Feb-14',
 'Reported 17-Feb-2014',
 '08-Feb-14',
 '07-Feb-14',
 '07-Feb-14',
 '26-Jan-14',
 '25-Jan-14',
 '04-Jan-14',
 '2014',
 '25-Dec-13',
 '16-Dec-13',
 '13-Dec-13',
 '11-Dec-13',
 '10-Dec-13',
 '05-Dec-13',
 '02-Dec-13',
 '30-Nov-13',
 '29-Nov-13',
 '23-Nov-13',
 '22-Nov-13',
 '12-Nov-13',
 '10-Nov-13',
 '07-Nov-13',
 '07-Nov-13',
 '31-Oct-13',
 '28-Oct-13',
 '26-Oct-13',
 '26-Oct-13',
 '24-Oct-13',
 '23-Oct-13',
 '20-Oct-13',
 '19-Oct-13',
 '11-Oct-13',
 '08-Oct-13',
 '06-Oct-13',
 '10-Oct-13',
 '29-Sep-13',
 '29-Sep-13',
 ' 25-Sep-2013',
 ' 21-Sep-2013',
 ' 21-Sep-2013',
 ' 14-Sep-2013',
 ' 12-Sep-2013',
 '08-Sep-13',
 ' 07-Sep-2013',
 ' 07-Sep-2013',
 ' 02-Sep-2013',
 ' 01-Sep-2013',
 ' 01-Sep-2013',
 ' 01-Sep-2013',
 '31-Aug-13',
 '31-Aug-13',
 '29-Aug-13',
 '26-Aug-13',
 ' 25-Aug-2013',
 ' 25-Aug-2013',
 ' 18-Aug-2013',
 '17-Aug-13',
 ' 14-Aug-2013',
 ' 13-Aug-2013',
 '11-Aug-13',
 'Reported 08-Aug-2013',
 ' 05-Aug-2013',
 '  31-Jul-2013',
 '  30-Jul-2013',
 '28-Jul-13',
 '  29-Jul-2013',
 '  29-Jul-2013',
 '28-Jul-13',
 '28-Jul-13',
 '    22-Jul-2013',
 '19-Jul-13',
 'Reported 17-Jul-2013',
 '15-Jul-13',
 '14-Jul-13',
 '11-Jul-13',
 '07-Jul-13',
 '02-Jul-13',
 '30-Jun-13',
 '27-Jun-13',
 '25-Jun-13',
 '25-Jun-13',
 '25-Jun-13',
 '18-Jun-13',
 '17-Jun-13',
 '16-Jun-13',
 '15-Jun-13',
 'Reported 14-Jun-2013',
 '06-Jun-13',
 '06-Jun-13',
 '27-May-13',
 '27-May-13',
 '23-May-13',
 '23-May-13',
 '14-May-14',
 '08-May-13',
 '08-May-13',
 '04-May-13',
 '28-Apr-13',
 '24-Apr-13',
 '21-Apr-13',
 '17-Apr-13',
 '14-Apr-13',
 '13-Apr-13',
 '13-Apr-13',
 '10-Apr-13',
 '04-Apr-13',
 'Reported 02-Apr-2013',
 '02-Apr-13',
 '31-Mar-13',
 '29-Mar-13',
 'Reported 21-Mar-2013',
 '21-Mar-13',
 '16-Mar-13',
 '16-Mar-13',
 '12-Mar-13',
 '10-Mar-13',
 '10-Mar-13',
 '03-Mar-13',
 '27-Feb-13',
 '21-Feb-13',
 '21-Feb-13',
 '10-Feb-13',
 '09-Feb-13',
 '01-Feb-13',
 '26-Jan-13',
 '25-Jan-13',
 'Reported 21-Jan-2013',
 '16-Jan-13',
 '13-Jan-13',
 '05-Jan-13',
 '31-Dec-12',
 '30-Dec-12',
 '28-Dec-12',
 '25-Dec-12',
 '19-Dec-12',
 '05-Dec-12',
 '02-Dec-12',
 'Dec-12',
 '30-Nov-12',
 '27-Nov-12',
 '22-Nov-12',
 '19-Nov-12',
 '04-Nov-12',
 '04-Nov-12',
 '30-Oct-12',
 '27-Oct-12',
 '23-Oct-12',
 '19-Oct-12',
 '18-Oct-12',
 '18-Oct-12',
 '16-Oct-12',
 'Reported 11-Oct-2012',
 '10-Oct-12',
 '02-Oct-12',
 '25-Sep-12',
 '24-Sep-12',
 '16-Sep-12',
 '10-Sep-12',
 '09-Sep-12',
 '08-Sep-12',
 '08-Sep-12',
 '06-Sep-12',
 '06-Sep-12',
 '04-Sep-12',
 '02-Sep-12',
 '02-Sep-12',
 '02-Sep-12',
 '31-Aug-12',
 '28-Aug-12',
 '26-Aug-12',
 '15-Aug-12',
 '11-Aug-12',
 '08-Aug-12',
 '06-Aug-12',
 '04-Aug-12',
 '31-Jul-12',
 '31-Jul-12',
 '30-Jul-12',
 '30-Jul-12',
 '24-Jul-12',
 '23-Jul-12',
 '21-Jul-12',
 '19-Jul-12',
 '14-Jul-12',
 '08-Jul-12',
 '07-Jul-12',
 '07-Jul-12',
 '07-Jul-12',
 '06-Jul-12',
 'Reported 28-Jun-2012',
 '26-Jun-12',
 '26-Jun-12',
 '26-Jun-12',
 '22-Jun-12',
 '22-Jun-12',
 '20-Jun-12',
 '19-Jun-12',
 '18-Jun-12',
 '15-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '12-Jun-12',
 '10-Jun-12',
 '03-Jun-12',
 '02-Jun-12',
 '02-Jun-12',
 '31-May-12',
 '29-May-12',
 '23-May-12',
 '20-May-12',
 '16-May-12',
 '12-May-12',
 '09-May-12',
 '06-May-12',
 '19-Apr-12',
 '19-Apr-12',
 '11-Apr-12',
 '03-Apr-12',
 'Apr-13',
 '31-Mar-12',
 '24-Mar-12',
 '22-Mar-12',
 '20-Mar-12',
 '15-Mar-12',
 '14-Mar-12',
 '14-Mar-12',
 '06-Mar-12',
 '06-Mar-12',
 '05-Mar-12',
 '04-Mar-12',
 '03-Mar-12',
 '01-Mar-12',
 '26-Feb-12',
 '25-Feb-12',
 '20-Feb-12',
 '06-Feb-12',
 'Reported 22-Jan-2012',
 '27-Jan-12',
 '19-Jan-12',
 '18-Jan-12',
 '18-Jan-12',
 '15-Jan-12',
 '13-Jan-12',
 '03-Jan-12',
 '02-Jan-12',
 '31-Dec-11',
 'Reported 26-Dec-2011',
 '25-Dec-11',
 '23-Dec-11',
 '21-Dec-11',
 '21-Dec-11',
 '11-Dec-11',
 '07-Dec-11',
 '07-Dec-11',
 '06-Dec-11',
 '05-Dec-11',
 '02-Dec-11',
 '29-Nov-11',
 '28-Nov-11',
 '22-Nov-11',
 'Reported 20-Nov-2011',
 '12-Nov-11',
 '11-Nov-11',
 '  29-Oct-2011',
 'Reported 28-Oct-2011',
 '  29-Oct-2011',
 '22-Oct-11',
 '20-Oct-11',
 '19-Oct-11',
 '11-Oct-11',
 '10-Oct-11',
 '09-Oct-11',
 '05-Oct-11',
 '02-Oct-11',
 '01-Oct-11',
 '30-Sep-11',
 '28-Sep-11',
 '28-Sep-11',
 '24-Sep-11',
 '24-Sep-11',
 '20-Sep-11',
 '19-Sep-11',
 '17-Sep-11',
 '16-Sep-11',
 '11-Sep-11',
 '11-Sep-11',
 '04-Sep-11',
 '04-Sep-11',
 '02-Sep-11',
 '31-Aug-11',
 '28-Aug-11',
 '28-Aug-11',
 '26-Aug-11',
 '24-Aug-11',
 '24-Aug-11',
 '23-Aug-11',
 '18-Aug-11',
 '17-Aug-11',
 '17-Aug-11',
 '17-Aug-11',
 '16-Aug-11',
 '16-Aug--2011',
 '16-Aug-11',
 '15-Aug-11',
 '11-Aug--2011',
 '01-Aug-11',
 '31-Jul-11',
 '30-Jul-11',
 '25-Jul-11',
 '22-Jul-11',
 '19-Jul-11',
 '15-Jul-11',
 '13-Jul-11',
 '13-Jul-11',
 '07-Jul-11',
 '07-Jul-11',
 '06-Jul-11',
 '05-Jul-11',
 '30-Jun-11',
 '29-Jun-11',
 '28-Jun-11',
 '26-Jun-08',
 '24-Jun-11',
 '21-Jun-11',
 '19-Jun-11',
 '19-Jun-11',
 '15-Jun-11',
 'Reported 14-Jun-2011',
 '12-Jun-11',
 'Reported 06-Jun-2011',
 '06-Jun-11',
 '06-Jun-11',
 '01-Jun-11',
 '30-May-11',
 '29-May-11',
 '25-May-11',
 '22-May-11',
 '21-May-11',
 '21-May-11',
 '13-May-11',
 '13-May-11',
 '10-May-11',
 'Reported 07-May-2011',
 '04-May-11',
 '26-Apr-11',
 '23-Apr-11',
 '22-Apr-11',
 '16-Apr-11',
 '13-Apr-11',
 '08-Apr-11',
 'Reported 29-Mar-2011',
 '24-Mar-11',
 '23-Mar-11',
 '21-Mar-11',
 '21-Mar-11',
 '16-Mar-11',
 'Reported 10-Mar-2010',
 '10-Mar-11',
 'Reported 28-Feb-2011',
 '23-Feb-11',
 '18-Feb-11',
 '17-Feb-11',
 '13-Feb-11',
 '12-Feb-11',
 'Reported 04-Feb-2011',
 '02-Feb-11',
 '31-Jan-11',
 '28-Jan-11',
 '26-Jan-11',
 '20-Jan-11',
 '15-Jan-11',
 'Reported 12-Jan 2011',
 '03-Jan-11',
 '26-Dec-10',
 '17-Dec-10',
 '11-Dec-10',
 '05-Dec-10',
 'Reported 03-Dec-2010',
 '01-Dec-10',
 '01-Dec-10',
 '30-Nov-10',
 '30-Nov-10',
 'Reported 27-Nov-2010',
 '27-Nov-10',
 '19-Nov-10',
 '15-Nov-10',
 '14-Nov-10',
 'Reported 12-Nov-2010',
 '30-Oct-10',
 'Reported 28-Oct-2010',
 '28-Oct-10',
 '25-Oct-10',
 '23-Oct-10',
 '23-Oct-10',
 '22-Oct-10',
 '20-Oct-10',
 '09-Oct-10',
 '02-Oct-10',
 '02-Oct-10',
 '01-Oct-10',
 '27-Sep-10',
 '24-Sep-10',
 '21-Sep-10',
 ' 13-Sep-2010',
 '07-Sep-10',
 'Reported 06-Sep-2010',
 ' 04-Sep-2010',
 '03-Sep-10',
 '03-Sep-10',
 '02-Sep-10',
 '29-Aug-10',
 '18-Aug-10',
 '17-Aug-10',
 '14-Aug-10',
 '10-Aug-10',
 '10-Aug-10',
 '08-Aug-10',
 '07-Aug-10',
 '07-Aug-10',
 '05-Aug-10',
 '02-Aug-10',
 '02-Aug-10',
 '25-Jul-10',
 '23-Jul-10',
 '19-Jul-10',
 '17-Jul-10',
 '17-Jul-10',
 '16-Jul-10',
 '16-Jul-10',
 '11-Jul-10',
 '04-Jul-10',
 '03-Jul-10',
 '02-Jul-10',
 '02-Jul-10',
 '27-Jun-10',
 '25-Jun-10',
 '25-Jun-10',
 '15-Jun-10',
 '10-Jun-10',
 '06-Jun-10',
 'Jun-10',
 '30-May-10',
 '18-May-10',
 '18-May-10',
 '18-May-10',
 '03-May-10',
 '01-May-10',
 '28-Apr-10',
 '19-Apr-10',
 '13-Apr-10',
 '04-Apr-10',
 ' 27-Mar-2010',
 '190Feb-2010',
 '16-Feb-10',
 '15-Feb-10',
 '13-Feb-10',
 '11-Feb-10',
 'Reported 06-Feb-2010',
 '06-Feb-10',
 '06-Feb-10',
 '04-Feb-10',
 '03-Feb-10',
 '01-Feb-10',
 '31-Jan-10',
 '27-Jan-10',
 '22-Jan-10',
 '22-Jan-10',
 '12-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '06-Jan-10',
 '05-Jan-10',
 '29-Dec-09',
 '26-Dec-09',
 '22-Dec-09',
 '20-Dec-09',
 '20-Dec-09',
 '18-Dec-09',
 '18-Dec-09',
 '16-Dec-09',
 '13-Dec-09',
 '12-Dec-09',
 '05-Dec-09',
 '25-Nov-09',
 '24-Nov-09',
 '16-Nov-09',
 '16-Nov-09',
 '13-Nov-09',
 '11-Nov-09',
 '08-Nov-09',
 '05-Nov-09',
 '30-Oct-09',
 'Reported 29-Oct-2009',
 '28-Oct-09',
 '24-Oct-09',
 '19-Oct-09',
 '18-Oct-09',
 '17-Oct-09',
 'Reported 14-Oct-2009',
 '09-Oct-09',
 '02-Oct-09',
 '26-Sep-09',
 '18-Sep-09',
 '15-Sep-09',
 '13-Sep-09',
 '12-Sep-09',
 '07-Sep-09',
 '02-Sep-09',
 '01-Sep-09',
 '30-Aug-09',
 '29-Aug-09',
 '25-Aug-09',
 '11-Aug-09',
 '10-Aug-09',
 '06-Aug-09',
 '01-Aug-09',
 '31-Jul-09',
 '30-Jul-09',
 '29-Jul-09',
 'Reported 24-Jul-2009',
 '24-Jul-09',
 '24-Jul-09',
 '22-Jul-09',
 '22-Jul-09',
 '18-Jul-09',
 '11-Jul-09',
 '11-Jul-09',
 '07-Jul-09',
 '05-Jul-09',
 '04-Jul-09',
 '27-Jun-09',
 '21-Jun-09',
 '16-Jun-09',
 'Reported 14-Jun-2009',
 '02-Jun-09',
 '02-Jun-09',
 '01-Jun-09',
 '31-May-09',
 '25-May-09',
 '17-May-09',
 '16-May-09',
 '16-May-09',
 '12-May-09',
 '06-Mar-09',
 '28-Apr-09',
 'Reported 25-Apr-2009',
 '21-Apr-09',
 '20-Apr-09',
 '19-Apr-09',
 '12-Apr-09',
 '17-Apr-09',
 '11-Apr-09',
 '06-Apr-09',
 '06-Apr-09',
 '03-Apr-09',
 '27-Mar-09',
 '21-Mar-09',
 '20-Mar-09',
 '19-Mar-09',
 '19-Mar-09',
 '18-Mar-09',
 'Reported 17-Mar-2009',
 '17-Mar-09',
 'Reported 16-Mar-2009',
 '06-Mar-09',
 '02-Mar-09',
 '01-Mar-09',
 '01-Mar-09',
 '22-Feb-09',
 '18-Feb-09',
 '12-Feb-09',
 '11-Feb-09',
 '08-Feb-09',
 '07-Feb-09',
 '07-Feb-09',
 'Reported 27-Jan-2009',
 'Reported 26-Jan-2009',
 '25-Jan-09',
 '24-Jan-09',
 '24-Jan-09',
 '24-Jan-09',
 '23-Jan-09',
 '18-Jan-09',
 '16-Jan-09',
 'Reported 13-Jan-2009',
 '12-Jan-09',
 '11-Jan-09',
 '11-Jan-09',
 '    10-Jan-2009',
 '10-Jan-09',
 '06-Jan-09',
 'Jan-09',
 '30-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '20-Dec-08',
 '14-Dec-08',
 '10-Dec-08',
 '06-Dec-06',
 'Dec-08',
 '28-Nov-08',
 '25-Nov-08',
 '24-Nov-08',
 '09-Nov-08',
 '09-Nov-08',
 '06-Nov-08',
 '22-Oct-08',
 '21-Oct-08',
 '12-Oct-08',
 '11-Oct-08',
 '08-Oct-08',
 '06-Oct-08',
 '28-Sep-08',
 '28-Sep-08',
 '15-Sep-08',
 '14-Sep-08',
 '09-Sep-08',
 '08-Sep-08',
 '07-Sep-08',
 '06-Sep-08',
 '06-Sep-08',
 '01-Sep-08',
 'Sep-08',
 '30-Aug-08',
 '30-Aug-08',
 '30-Aug-08',
 '28-Aug-08',
 '27-Aug-08',
 '24-Aug-08',
 '24-Aug-08',
 '20-Aug-08',
 '18-Aug-08',
 '16-Aug-08',
 '12-Aug-08',
 '11-Aug-08',
 ...]

In [29]:
[i.strip('Rep rotd') for i in df2.Date.tolist()]
#strip removes all from the right and the left of the string

['18-Sep-16',
 '18-Sep-16',
 '18-Sep-16',
 '17-Sep-16',
 '16-Sep-16',
 '15-Sep-16',
 '11-Sep-16',
 '07-Sep-16',
 '06-Sep-16',
 '05-Sep-16',
 '05-Sep-16',
 '04-Sep-16',
 '01-Sep-16',
 '29-Aug-16',
 '29-Aug-16',
 '27-Aug-16',
 '25-Aug-16',
 '07-Aug-16',
 '06-Aug-16',
 '04-Aug-16',
 '29-Jul-16',
 '28-Jul-16',
 '28-Jul-16',
 '27-Jul-16',
 '26-Jul-16',
 '24-Jul-16',
 '23-Jul-16',
 '23-Jul-16',
 '20-Jul-16',
 '17-Jul-16',
 '16-Jul-16',
 '16-Jul-16',
 '15-Jul-16',
 '14-Jul-2016',
 '08-Jul-2016',
 '08-Jul-16',
 '07-Jul-16',
 '07-Jul-16',
 '06-Jul-16',
 '04-Jul-16',
 '27-Jun-16',
 '25-Jun-16',
 '24-Jun-16',
 '23-Jun-16',
 '21-Jun-16',
 '21-Jun-16',
 '15-Jun-16',
 '15-Jun-16',
 '14-Jun-16',
 '11-Jun-16',
 '07-Jun-16',
 '05-Jun-16',
 '05-Jun-16',
 '04-Jun-16',
 '02-Jun-16',
 '02-Jun-16',
 '31-May-16',
 '29-May-16',
 '29-May-16',
 '22-May-16',
 '21-May-16',
 '21-May-16',
 '18-May-16',
 '15-May-16',
 '03-May-16',
 '02-May-16',
 '25-Apr-16',
 '23-Apr-16',
 '22-Apr-16',
 '19-Apr-16',
 '18-Apr-16',
 '13-Apr-16',
 '09-Apr-16',
 '08-Apr-16',
 '07-Apr-16',
 '07-Apr-16',
 '31-Mar-16',
 '30-Mar-16',
 '28-Mar-16',
 '28-Mar-16',
 '26-Mar-16',
 '13-Mar-16',
 '11-Mar-16',
 '10-Mar-16',
 '04-Mar-16',
 '03-Mar-2016',
 '02-Mar-16',
 '22-Feb-16',
 '19-Feb-2016',
 '12-Feb-16',
 '10-Feb-2016',
 '10-Feb-16',
 '05-Feb-16',
 '04-Feb-16',
 '29-Jan-16',
 '28-Jan-16',
 '25-Jan-16',
 '24-Jan-16',
 '24-Jan-16',
 '23-Jan-16',
 '11-Jan-2016',
 '05-Jan-16',
 '02-Jan-16',
 '26-Dec-15',
 '25-Dec-15',
 '22-Dec-15',
 '21-Dec-15',
 '21-Dec-15',
 '19-Dec-15',
 '13-Dec-15',
 '11-Dec-15',
 '08-Dec-15',
 '16-Nov-15',
 '15-Nov-15',
 '15-Nov-15',
 '10-Nov-15',
 '07-Nov-15',
 '03-Nov-15',
 '01-Nov-15',
 '01-Nov-15',
 '30-Oct-15',
 '28-Oct-15',
 '25-Oct-15',
 '21-Oct-15',
 '19-Oct-15',
 '17-Oct-15',
 '17-Oct-15',
 '17-Oct-15',
 '13-Oct-15',
 '09-Oct-15',
 '09-Oct-15',
 '08-Oct-15',
 '07-Oct-15',
 '05-Oct-15',
 '05-Oct-15',
 '04-Oct-15',
 '29-Sep-15',
 '26-Sep-15',
 '24-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '20-Sep-15',
 '18-Sep-15',
 '17-Sep-15',
 '08-Sep-15',
 '06-Sep-15',
 '05-Sep-15',
 '04-Sep-15',
 '03-Sep-15',
 '01-Sep-15',
 'Sep-15',
 '29-Aug-15',
 '29-Aug-15',
 '22-Aug-15',
 '22-Aug-15',
 '20-Aug-15',
 '19-Aug-15',
 '18-Aug-15',
 '18-Aug-15',
 '10-Aug-15',
 '31-Jul-15',
 '26-Jul-15',
 '26-Jul-15',
 '25-Jul-15',
 '23-Jul-15',
 '23-Jul-15',
 '22-Jul-15',
 '19-Jul-15',
 '10-Jul-15',
 '08-Jul-15',
 '06-Jul-15',
 '04-Jul-15',
 '04-Jul-15',
 '03-Jul-15',
 '02-Jul-15',
 '01-Jul-15',
 '30-Jun-15',
 '30-Jun-15',
 '27-Jun-15',
 '27-Jun-15',
 '26-Jun-15',
 '26-Jun-15',
 '26-Jun-15',
 '25-Jun-2015',
 '25-Jun-15',
 '24-Jun-15',
 '24-Jun-15',
 '23-Jun-15',
 '19-Jun-15',
 '17-Jun-15',
 '14-Jun-15',
 '14-Jun-15',
 '13-Jun-15',
 '11-Jun-15',
 '07-Jun-15',
 '05-Jun-15',
 '01-Jun-15',
 '29-May-15',
 '29-May-15',
 '25-May-15',
 '24-May-15',
 '20-May-15',
 '15-May-15',
 '09-May-15',
 '07-May-15',
 '03-May-15',
 '02-May-15',
 '29-Apr-15',
 '26-Apr-15',
 '25-Apr-15',
 '24-Jun-15',
 '13-Apr-15',
 '11-Apr-15',
 '12-Apr-15',
 '31-Mar-15',
 '03-Apr-15',
 '29-Mar-15',
 '26-Mar-15',
 '21-Mar-15',
 '18-Mar-15',
 '16-Mar-15',
 '11-Mar-15',
 '10-Mar-15',
 '07-Mar-15',
 '15-Feb-15',
 '14-Feb-15',
 '09-Feb-15',
 '08-Feb-15',
 '05-Feb-15',
 '30-Jan-15',
 '27-Jan-15',
 '24-Jan-15',
 '19-Jan-15',
 '19-Jan-15',
 '17-Jan-15',
 '16-Jan-15',
 '08-Jan-15',
 '06-Jan-15',
 '03-Jan-15',
 '01-Jan-15',
 '29-Dec-14',
 '29-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 '28-Dec-14',
 '23-Dec-2014',
 '15-Dec-14',
 '03-Dec-2014',
 '29-Nov-14',
 '20-Nov-14',
 '19-Nov-14',
 '16-Nov-14',
 '17-Nov-2014',
 '13-Nov-14',
 '10-Nov-14',
 '08-Nov-14',
 '31-Oct-14',
 '29-Oct-14',
 '22-Oct-14',
 '20-Oct-14',
 '19-Oct-14',
 '18-Oct-14',
 '17-Oct-14',
 '14-Oct-14',
 '12-Oct-14',
 '07-Oct-14',
 '11-Oct-14',
 '05-Oct-14',
 '05-Oct-14',
 '03-Oct-14',
 '03-Oct-14',
 '02-Oct-14',
 '02-Oct-14',
 '21-Sep-14',
 '12-Sep-2014',
 '13-Sep-14',
 '09-Sep-14',
 '06-Sep-14',
 '03-Sep-14',
 '02-Sep-14',
 'Sep-14',
 '31-Aug-14',
 '29-Aug-14',
 '29-Aug-14',
 '28-Aug-14',
 '27-Aug-14',
 '27-Aug-14',
 '27-Aug-14',
 '25-Aug-2014',
 '24-Aug-14',
 '16-Aug-14',
 '12-Aug-14',
 '10-Aug-14',
 '09-Aug-14',
 '09-Aug-14',
 '08-Aug-14',
 '06-Aug-14',
 '05-Aug-14',
 '02-Aug-14',
 '02-Aug-14',
 '01-Aug-14',
 'Aug-14',
 '27-Jul-14',
 '22-Jul-14',
 '21-Jul-14',
 '20-Jul-14',
 '16-Jul-14',
 '14-Jul-14',
 '13-Jul-14',
 '12-Jul-14',
 '09-Jul-14',
 '05-Jul-14',
 '05-Jul-14',
 '03-Jul-14',
 '27-Jun-2014',
 '25-Jun-14',
 '18-Jun-14',
 '18-Jun-14',
 '17-Jun-2014',
 '09-Jun-14',
 '09-Jun-14',
 '09-Jun-14',
 '08-Jun-14',
 '07-Jun-14',
 '01-Jun-14',
 '01-Jun-14',
 '01-Jun-14',
 '24-May-14',
 '23-May-14',
 '22-May-14',
 '20-Nov-15',
 '15-May-14',
 '14-May-14',
 '13-May-14',
 '11-May-14',
 '10-May-2014',
 '06-May-14',
 '01-May-14',
 '24-Apr-14',
 '22-Apr-14',
 '15-Apr-14',
 '12-Apr-2014',
 '12-Apr-14',
 '04-Apr-14',
 '04-Apr-14',
 '03-Apr-14',
 '29-Mar-14',
 '22-Mar-14',
 '22-Mar-14',
 '21-Mar-14',
 '18-Mar-14',
 '18-Mar-14',
 '13-Mar-14',
 '18-Mar-14',
 '12-Mar-14',
 '02-Mar-14',
 '20-Feb-14',
 '17-Feb-2014',
 '08-Feb-14',
 '07-Feb-14',
 '07-Feb-14',
 '26-Jan-14',
 '25-Jan-14',
 '04-Jan-14',
 '2014',
 '25-Dec-13',
 '16-Dec-13',
 '13-Dec-13',
 '11-Dec-13',
 '10-Dec-13',
 '05-Dec-13',
 '02-Dec-13',
 '30-Nov-13',
 '29-Nov-13',
 '23-Nov-13',
 '22-Nov-13',
 '12-Nov-13',
 '10-Nov-13',
 '07-Nov-13',
 '07-Nov-13',
 '31-Oct-13',
 '28-Oct-13',
 '26-Oct-13',
 '26-Oct-13',
 '24-Oct-13',
 '23-Oct-13',
 '20-Oct-13',
 '19-Oct-13',
 '11-Oct-13',
 '08-Oct-13',
 '06-Oct-13',
 '10-Oct-13',
 '29-Sep-13',
 '29-Sep-13',
 '25-Sep-2013',
 '21-Sep-2013',
 '21-Sep-2013',
 '14-Sep-2013',
 '12-Sep-2013',
 '08-Sep-13',
 '07-Sep-2013',
 '07-Sep-2013',
 '02-Sep-2013',
 '01-Sep-2013',
 '01-Sep-2013',
 '01-Sep-2013',
 '31-Aug-13',
 '31-Aug-13',
 '29-Aug-13',
 '26-Aug-13',
 '25-Aug-2013',
 '25-Aug-2013',
 '18-Aug-2013',
 '17-Aug-13',
 '14-Aug-2013',
 '13-Aug-2013',
 '11-Aug-13',
 '08-Aug-2013',
 '05-Aug-2013',
 '31-Jul-2013',
 '30-Jul-2013',
 '28-Jul-13',
 '29-Jul-2013',
 '29-Jul-2013',
 '28-Jul-13',
 '28-Jul-13',
 '22-Jul-2013',
 '19-Jul-13',
 '17-Jul-2013',
 '15-Jul-13',
 '14-Jul-13',
 '11-Jul-13',
 '07-Jul-13',
 '02-Jul-13',
 '30-Jun-13',
 '27-Jun-13',
 '25-Jun-13',
 '25-Jun-13',
 '25-Jun-13',
 '18-Jun-13',
 '17-Jun-13',
 '16-Jun-13',
 '15-Jun-13',
 '14-Jun-2013',
 '06-Jun-13',
 '06-Jun-13',
 '27-May-13',
 '27-May-13',
 '23-May-13',
 '23-May-13',
 '14-May-14',
 '08-May-13',
 '08-May-13',
 '04-May-13',
 '28-Apr-13',
 '24-Apr-13',
 '21-Apr-13',
 '17-Apr-13',
 '14-Apr-13',
 '13-Apr-13',
 '13-Apr-13',
 '10-Apr-13',
 '04-Apr-13',
 '02-Apr-2013',
 '02-Apr-13',
 '31-Mar-13',
 '29-Mar-13',
 '21-Mar-2013',
 '21-Mar-13',
 '16-Mar-13',
 '16-Mar-13',
 '12-Mar-13',
 '10-Mar-13',
 '10-Mar-13',
 '03-Mar-13',
 '27-Feb-13',
 '21-Feb-13',
 '21-Feb-13',
 '10-Feb-13',
 '09-Feb-13',
 '01-Feb-13',
 '26-Jan-13',
 '25-Jan-13',
 '21-Jan-2013',
 '16-Jan-13',
 '13-Jan-13',
 '05-Jan-13',
 '31-Dec-12',
 '30-Dec-12',
 '28-Dec-12',
 '25-Dec-12',
 '19-Dec-12',
 '05-Dec-12',
 '02-Dec-12',
 'Dec-12',
 '30-Nov-12',
 '27-Nov-12',
 '22-Nov-12',
 '19-Nov-12',
 '04-Nov-12',
 '04-Nov-12',
 '30-Oct-12',
 '27-Oct-12',
 '23-Oct-12',
 '19-Oct-12',
 '18-Oct-12',
 '18-Oct-12',
 '16-Oct-12',
 '11-Oct-2012',
 '10-Oct-12',
 '02-Oct-12',
 '25-Sep-12',
 '24-Sep-12',
 '16-Sep-12',
 '10-Sep-12',
 '09-Sep-12',
 '08-Sep-12',
 '08-Sep-12',
 '06-Sep-12',
 '06-Sep-12',
 '04-Sep-12',
 '02-Sep-12',
 '02-Sep-12',
 '02-Sep-12',
 '31-Aug-12',
 '28-Aug-12',
 '26-Aug-12',
 '15-Aug-12',
 '11-Aug-12',
 '08-Aug-12',
 '06-Aug-12',
 '04-Aug-12',
 '31-Jul-12',
 '31-Jul-12',
 '30-Jul-12',
 '30-Jul-12',
 '24-Jul-12',
 '23-Jul-12',
 '21-Jul-12',
 '19-Jul-12',
 '14-Jul-12',
 '08-Jul-12',
 '07-Jul-12',
 '07-Jul-12',
 '07-Jul-12',
 '06-Jul-12',
 '28-Jun-2012',
 '26-Jun-12',
 '26-Jun-12',
 '26-Jun-12',
 '22-Jun-12',
 '22-Jun-12',
 '20-Jun-12',
 '19-Jun-12',
 '18-Jun-12',
 '15-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '14-Jun-12',
 '12-Jun-12',
 '10-Jun-12',
 '03-Jun-12',
 '02-Jun-12',
 '02-Jun-12',
 '31-May-12',
 '29-May-12',
 '23-May-12',
 '20-May-12',
 '16-May-12',
 '12-May-12',
 '09-May-12',
 '06-May-12',
 '19-Apr-12',
 '19-Apr-12',
 '11-Apr-12',
 '03-Apr-12',
 'Apr-13',
 '31-Mar-12',
 '24-Mar-12',
 '22-Mar-12',
 '20-Mar-12',
 '15-Mar-12',
 '14-Mar-12',
 '14-Mar-12',
 '06-Mar-12',
 '06-Mar-12',
 '05-Mar-12',
 '04-Mar-12',
 '03-Mar-12',
 '01-Mar-12',
 '26-Feb-12',
 '25-Feb-12',
 '20-Feb-12',
 '06-Feb-12',
 '22-Jan-2012',
 '27-Jan-12',
 '19-Jan-12',
 '18-Jan-12',
 '18-Jan-12',
 '15-Jan-12',
 '13-Jan-12',
 '03-Jan-12',
 '02-Jan-12',
 '31-Dec-11',
 '26-Dec-2011',
 '25-Dec-11',
 '23-Dec-11',
 '21-Dec-11',
 '21-Dec-11',
 '11-Dec-11',
 '07-Dec-11',
 '07-Dec-11',
 '06-Dec-11',
 '05-Dec-11',
 '02-Dec-11',
 '29-Nov-11',
 '28-Nov-11',
 '22-Nov-11',
 '20-Nov-2011',
 '12-Nov-11',
 '11-Nov-11',
 '29-Oct-2011',
 '28-Oct-2011',
 '29-Oct-2011',
 '22-Oct-11',
 '20-Oct-11',
 '19-Oct-11',
 '11-Oct-11',
 '10-Oct-11',
 '09-Oct-11',
 '05-Oct-11',
 '02-Oct-11',
 '01-Oct-11',
 '30-Sep-11',
 '28-Sep-11',
 '28-Sep-11',
 '24-Sep-11',
 '24-Sep-11',
 '20-Sep-11',
 '19-Sep-11',
 '17-Sep-11',
 '16-Sep-11',
 '11-Sep-11',
 '11-Sep-11',
 '04-Sep-11',
 '04-Sep-11',
 '02-Sep-11',
 '31-Aug-11',
 '28-Aug-11',
 '28-Aug-11',
 '26-Aug-11',
 '24-Aug-11',
 '24-Aug-11',
 '23-Aug-11',
 '18-Aug-11',
 '17-Aug-11',
 '17-Aug-11',
 '17-Aug-11',
 '16-Aug-11',
 '16-Aug--2011',
 '16-Aug-11',
 '15-Aug-11',
 '11-Aug--2011',
 '01-Aug-11',
 '31-Jul-11',
 '30-Jul-11',
 '25-Jul-11',
 '22-Jul-11',
 '19-Jul-11',
 '15-Jul-11',
 '13-Jul-11',
 '13-Jul-11',
 '07-Jul-11',
 '07-Jul-11',
 '06-Jul-11',
 '05-Jul-11',
 '30-Jun-11',
 '29-Jun-11',
 '28-Jun-11',
 '26-Jun-08',
 '24-Jun-11',
 '21-Jun-11',
 '19-Jun-11',
 '19-Jun-11',
 '15-Jun-11',
 '14-Jun-2011',
 '12-Jun-11',
 '06-Jun-2011',
 '06-Jun-11',
 '06-Jun-11',
 '01-Jun-11',
 '30-May-11',
 '29-May-11',
 '25-May-11',
 '22-May-11',
 '21-May-11',
 '21-May-11',
 '13-May-11',
 '13-May-11',
 '10-May-11',
 '07-May-2011',
 '04-May-11',
 '26-Apr-11',
 '23-Apr-11',
 '22-Apr-11',
 '16-Apr-11',
 '13-Apr-11',
 '08-Apr-11',
 '29-Mar-2011',
 '24-Mar-11',
 '23-Mar-11',
 '21-Mar-11',
 '21-Mar-11',
 '16-Mar-11',
 '10-Mar-2010',
 '10-Mar-11',
 '28-Feb-2011',
 '23-Feb-11',
 '18-Feb-11',
 '17-Feb-11',
 '13-Feb-11',
 '12-Feb-11',
 '04-Feb-2011',
 '02-Feb-11',
 '31-Jan-11',
 '28-Jan-11',
 '26-Jan-11',
 '20-Jan-11',
 '15-Jan-11',
 '12-Jan 2011',
 '03-Jan-11',
 '26-Dec-10',
 '17-Dec-10',
 '11-Dec-10',
 '05-Dec-10',
 '03-Dec-2010',
 '01-Dec-10',
 '01-Dec-10',
 '30-Nov-10',
 '30-Nov-10',
 '27-Nov-2010',
 '27-Nov-10',
 '19-Nov-10',
 '15-Nov-10',
 '14-Nov-10',
 '12-Nov-2010',
 '30-Oct-10',
 '28-Oct-2010',
 '28-Oct-10',
 '25-Oct-10',
 '23-Oct-10',
 '23-Oct-10',
 '22-Oct-10',
 '20-Oct-10',
 '09-Oct-10',
 '02-Oct-10',
 '02-Oct-10',
 '01-Oct-10',
 '27-Sep-10',
 '24-Sep-10',
 '21-Sep-10',
 '13-Sep-2010',
 '07-Sep-10',
 '06-Sep-2010',
 '04-Sep-2010',
 '03-Sep-10',
 '03-Sep-10',
 '02-Sep-10',
 '29-Aug-10',
 '18-Aug-10',
 '17-Aug-10',
 '14-Aug-10',
 '10-Aug-10',
 '10-Aug-10',
 '08-Aug-10',
 '07-Aug-10',
 '07-Aug-10',
 '05-Aug-10',
 '02-Aug-10',
 '02-Aug-10',
 '25-Jul-10',
 '23-Jul-10',
 '19-Jul-10',
 '17-Jul-10',
 '17-Jul-10',
 '16-Jul-10',
 '16-Jul-10',
 '11-Jul-10',
 '04-Jul-10',
 '03-Jul-10',
 '02-Jul-10',
 '02-Jul-10',
 '27-Jun-10',
 '25-Jun-10',
 '25-Jun-10',
 '15-Jun-10',
 '10-Jun-10',
 '06-Jun-10',
 'Jun-10',
 '30-May-10',
 '18-May-10',
 '18-May-10',
 '18-May-10',
 '03-May-10',
 '01-May-10',
 '28-Apr-10',
 '19-Apr-10',
 '13-Apr-10',
 '04-Apr-10',
 '27-Mar-2010',
 '190Feb-2010',
 '16-Feb-10',
 '15-Feb-10',
 '13-Feb-10',
 '11-Feb-10',
 '06-Feb-2010',
 '06-Feb-10',
 '06-Feb-10',
 '04-Feb-10',
 '03-Feb-10',
 '01-Feb-10',
 '31-Jan-10',
 '27-Jan-10',
 '22-Jan-10',
 '22-Jan-10',
 '12-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '09-Jan-10',
 '06-Jan-10',
 '05-Jan-10',
 '29-Dec-09',
 '26-Dec-09',
 '22-Dec-09',
 '20-Dec-09',
 '20-Dec-09',
 '18-Dec-09',
 '18-Dec-09',
 '16-Dec-09',
 '13-Dec-09',
 '12-Dec-09',
 '05-Dec-09',
 '25-Nov-09',
 '24-Nov-09',
 '16-Nov-09',
 '16-Nov-09',
 '13-Nov-09',
 '11-Nov-09',
 '08-Nov-09',
 '05-Nov-09',
 '30-Oct-09',
 '29-Oct-2009',
 '28-Oct-09',
 '24-Oct-09',
 '19-Oct-09',
 '18-Oct-09',
 '17-Oct-09',
 '14-Oct-2009',
 '09-Oct-09',
 '02-Oct-09',
 '26-Sep-09',
 '18-Sep-09',
 '15-Sep-09',
 '13-Sep-09',
 '12-Sep-09',
 '07-Sep-09',
 '02-Sep-09',
 '01-Sep-09',
 '30-Aug-09',
 '29-Aug-09',
 '25-Aug-09',
 '11-Aug-09',
 '10-Aug-09',
 '06-Aug-09',
 '01-Aug-09',
 '31-Jul-09',
 '30-Jul-09',
 '29-Jul-09',
 '24-Jul-2009',
 '24-Jul-09',
 '24-Jul-09',
 '22-Jul-09',
 '22-Jul-09',
 '18-Jul-09',
 '11-Jul-09',
 '11-Jul-09',
 '07-Jul-09',
 '05-Jul-09',
 '04-Jul-09',
 '27-Jun-09',
 '21-Jun-09',
 '16-Jun-09',
 '14-Jun-2009',
 '02-Jun-09',
 '02-Jun-09',
 '01-Jun-09',
 '31-May-09',
 '25-May-09',
 '17-May-09',
 '16-May-09',
 '16-May-09',
 '12-May-09',
 '06-Mar-09',
 '28-Apr-09',
 '25-Apr-2009',
 '21-Apr-09',
 '20-Apr-09',
 '19-Apr-09',
 '12-Apr-09',
 '17-Apr-09',
 '11-Apr-09',
 '06-Apr-09',
 '06-Apr-09',
 '03-Apr-09',
 '27-Mar-09',
 '21-Mar-09',
 '20-Mar-09',
 '19-Mar-09',
 '19-Mar-09',
 '18-Mar-09',
 '17-Mar-2009',
 '17-Mar-09',
 '16-Mar-2009',
 '06-Mar-09',
 '02-Mar-09',
 '01-Mar-09',
 '01-Mar-09',
 '22-Feb-09',
 '18-Feb-09',
 '12-Feb-09',
 '11-Feb-09',
 '08-Feb-09',
 '07-Feb-09',
 '07-Feb-09',
 '27-Jan-2009',
 '26-Jan-2009',
 '25-Jan-09',
 '24-Jan-09',
 '24-Jan-09',
 '24-Jan-09',
 '23-Jan-09',
 '18-Jan-09',
 '16-Jan-09',
 '13-Jan-2009',
 '12-Jan-09',
 '11-Jan-09',
 '11-Jan-09',
 '10-Jan-2009',
 '10-Jan-09',
 '06-Jan-09',
 'Jan-09',
 '30-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '27-Dec-08',
 '20-Dec-08',
 '14-Dec-08',
 '10-Dec-08',
 '06-Dec-06',
 'Dec-08',
 '28-Nov-08',
 '25-Nov-08',
 '24-Nov-08',
 '09-Nov-08',
 '09-Nov-08',
 '06-Nov-08',
 '22-Oct-08',
 '21-Oct-08',
 '12-Oct-08',
 '11-Oct-08',
 '08-Oct-08',
 '06-Oct-08',
 '28-Sep-08',
 '28-Sep-08',
 '15-Sep-08',
 '14-Sep-08',
 '09-Sep-08',
 '08-Sep-08',
 '07-Sep-08',
 '06-Sep-08',
 '06-Sep-08',
 '01-Sep-08',
 'Sep-08',
 '30-Aug-08',
 '30-Aug-08',
 '30-Aug-08',
 '28-Aug-08',
 '27-Aug-08',
 '24-Aug-08',
 '24-Aug-08',
 '20-Aug-08',
 '18-Aug-08',
 '16-Aug-08',
 '12-Aug-08',
 '11-Aug-08',
 ...]

In [30]:
l=[k for i in df2.Date.tolist() for j in i.split() for k in j.split('-')]

In [ ]:
#month pattern = [A-Z a-z]{3,} for date

In [31]:
df3=df2.drop('Date', axis=1)
df3.shape
#Date dropped as we have replace it with new created Month col

(5865, 22)

# month is done now

In [32]:
df3.Activity.sample(50)

429                                       Walking in surf
5401                                             Swimming
5756                                                  NaN
3493    Greek steamship Lakonia caught fire, 98 of her...
2971                                         Spearfishing
4704                                             Swimming
2099                                  Chumming for sharks
4964                                         Dry shelling
4906                                             Swimming
5452    Swimming to shore after boat capsized by a squall
530                                               Fishing
2474    Swimming in strong current with 3 others when ...
5073           Swimming (recovering remains of Stilwell)
699                                          Spearfishing
5239                                             Swimming
746                                                Diving
4927                 Dived onto shark from floating stage
1687                                         Spearfishing
2498                                               Diving
813                                              Swimming
443                                               Surfing
5732                                            Swimming
1641    Scallop diving (using surface-supplied air & a...
1367                                              Surfing
2013                                         Wade-fishing
5511                  Sea disaster : Wreck of the Taiaroa
3309    The shrimper Loless Maurine capsized in heavy ...
734                                         Body boarding
4319                                             Swimming
3420              Spearfishing, but standing in the water
3438                                             Swimming
4000                              Free diving for sinkers
2732                                   Ran into the water
4538                                              Fishing
3531                  Washed into sea while picking opihi
5062      Taking wife to beach & about 1 m from the shore
1879                                Wading with surfboard
2142                                             Standing
5575                                   Diving for sponges
1141                                        Body boarding
472                                               Surfing
166                                               Surfing
837                                              Swimming
2852                                             Swimming
3437                                             Swimming
5443                                         Dress diving
2576                                              Surfing
851                                               Surfing
4607                                            Swimming
3954                    Fishing, walking in river to cast
Name: Activity, dtype: object

In [33]:
df3.Activity.value_counts()

Surfing                                                                                                                                                                                                                                     903
Swimming                                                                                                                                                                                                                                    804
Fishing                                                                                                                                                                                                                                     407
Spearfishing                                                                                                                                                                                                                                321
Bathing                                                                                                                                                                                                                                     150
Wading                                                                                                                                                                                                                                      142
Diving                                                                                                                                                                                                                                      111
Standing                                                                                                                                                                                                                                     95
Snorkeling                                                                                                                                                                                                                                   76
Scuba diving                                                                                                                                                                                                                                 73
Body boarding                                                                                                                                                                                                                                54
Body surfing                                                                                                                                                                                                                                 48
Swimming                                                                                                                                                                                                                                     47
Treading water                                                                                                                                                                                                                               32
Boogie boarding                                                                                                                                                                                                                              28
Kayaking                                                                                                                                                                                                                                     28
Pearl diving                                                                                                                                                                                                                                 28
Free diving                                                                                                                                                                                                                                  24
Fell overboard                                                                                                                                                                                                                               21
Windsurfing                                                                                                                                                                                                                                  18
Boogie Boarding                                                                                                                                                                                                                              16
Shark fishing                                                                                                                                                                                                                                15
Walking                                                                                                                                                                                                                                      15
Fishing                                                                                                                                                                                                                                      12
Rowing                                                                                                                                                                                                                                       12
Floating                                                                                                                                                                                                                                     12
Surf skiing                                                                                                                                                                                                                                  12
Surf-skiing                                                                                                                                                                                                                                  12
Surf fishing                                                                                                                                                                                                                                 11
Fishing for sharks                                                                                                                                                                                                                           11
                                                                                                                                                                                                                                           ...
Conch diver                                                                                                                                                                                                                                   1
3,909-ton Panamanian freighter Chieh Lee sank in a typhoon                                                                                                                                                                                    1
Snorkeling (filming the sardine run)                                                                                                                                                                                                          1
Fishing in waist-deep water                                                                                                                                                                                                                   1
Went over side of boat at trochus ground                                                                                                                                                                                                      1
Restraining a beached shark                                                                                                                                                                                                                   1
Washing horses                                                                                                                                                                                                                                1
Wreck of the steamship Birkenhead                                                                                                                                                                                                             1
Copra vessel with 19 on board was wrecked in a squall                                                                                                                                                                                         1
Lying on surfboard                                                                                                                                                                                                                            1
Swimming to shore from the Medic                                                                                                                                                                                                              1
Skindiving for specimens                                                                                                                                                                                                                      1
Towing her sister on plastic ski board                                                                                                                                                                                                        1
Swimming outside the safety enclosure attempting to retrieve a tennis ball drifting toward midstream                                                                                                                                          1
B-24 aircraft crashed  into the sea                                                                                                                                                                                                           1
Spearfishing / night diving                                                                                                                                                                                                                   1
Attempting to Kite surf from Egypt to Saudi Arabia                                                                                                                                                                                            1
Dutch merchant ship Zaandam torpedoed  by the U-174 amidships, sank & dozens of survivors took to rafts & boats. One man, Izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down      1
Diving, retrieving fish caught in net                                                                                                                                                                                                         1
Boat capsized                                                                                                                                                                                                                                 1
2 messboys (Jeppsen) & Tony Latona (13) were playing on the afterdeck of the Danish ship Grete Maersk. Jeppsen fell overboard, Latona threw a lifebelt then jumped in to help him. Ship didnt notice they were missing                       1
Freediving for seashells                                                                                                                                                                                                                      1
Bathing in 3' to 4' of water                                                                                                                                                                                                                  1
Swimming outside fishing net                                                                                                                                                                                                                  1
Shipwrecked; adrift on raft for 2 days & 2 nights                                                                                                                                                                                             1
Fishing with hand net in 2' of water                                                                                                                                                                                                          1
Filming a documentary                                                                                                                                                                                                                         1
Night diving                                                                                                                                                                                                                                  1
Swimming from capsized boat                                                                                                                                                                                                                   1
Helmet diving in Miami Seaquarium                                                                                                                                                                                                             1
Name: Activity, Length: 1453, dtype: int64

In [34]:
len(df3.Activity)

5865

In [35]:
activity_nona=df3.Activity[df3.Activity.isna()==False]

In [36]:
l=[j.strip(',.:\/&').lower().replace('ing','') for i in activity_nona for j in i.split()]

In [38]:
import pandas as pd

words_pd=pd.Series(l)
words_pd.value_counts()

surf          1080
swimm         1036
fish           752
div            495
spearfish      414
the            346
               259
in             235
a              222
on             204
for            201
water          191
to             176
bath           176
shark          172
wad            169
board          157
of             156
from           154
boat           147
stand          143
scuba          134
body           126
with           101
snorkel         88
overboard       86
fell            86
by              86
free            86
into            73
              ...
sobella          1
wooden           1
jack             1
pleasure         1
u-126            1
vinci            1
model            1
bolivar          1
rover            1
motorized        1
accident         1
44               1
u-134            1
black            1
trader           1
scotia           1
avocet           1
seeds            1
luis             1
electronic       1
load             1
32               1
o'ahu            1
shot)            1
heavily          1
gill             1
afterwards       1
1941             1
wilcox           1
dozens           1
Length: 1992, dtype: int64

In [39]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\anast\anaconda3\lib\site-packages (3.4)
Requirement already satisfied: six in c:\users\anast\anaconda3\lib\site-packages (from nltk) (1.12.0)
Requirement already satisfied: singledispatch in c:\users\anast\anaconda3\lib\site-packages (from nltk) (3.4.0.3)

In [40]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anast\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [43]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))
l=[w for w in l if not w in stop_words]
words_df=pd.Series(l)
words_df.value_counts()

surf              1080
swimm             1036
fish               752
div                495
spearfish          414
                   259
water              191
bath               176
shark              172
wad                169
board              157
boat               147
stand              143
scuba              134
body               126
snorkel             88
overboard           86
fell                86
free                86
capsized            67
sea                 63
ship                55
boogie              52
sharks              52
float               51
kayak               51
tread               49
sank                39
net                 37
pearl               36
                  ...
documentary          1
police               1
stratocruiser        1
circuit              1
angl                 1
copra                1
vehicle              1
notice               1
"boat                1
sobella              1
engagement           1
dynamit              1
heavily              1
gill                 1
afterwards           1
1941                 1
wilcox               1
44                   1
accident             1
motorized            1
rover                1
long                 1
quinqueradiata       1
master               1
"swimm               1
goggle-div           1
docks                1
dhow                 1
kormoran             1
wate                 1
Length: 1922, dtype: int64

In [44]:
bow=list(words_df.value_counts()[:10].index)

In [45]:
bow.remove('')

In [46]:
bow.remove('spearfish')

In [47]:
bow[1]='swim'

In [48]:
bow

['surf', 'swim', 'fish', 'div', 'water', 'bath', 'shark', 'wad']

In [49]:

import numpy as np

lst=[]
for i in df3.Activity:
    lst.append([j for j in bow if j in str(i).lower()])
df3['new act']=lst
df3[['new act','Activity']]

      new act                                           Activity
0      [surf]                                            Surfing
1      [surf]                                            Surfing
2      [surf]                                            Surfing
3      [surf]                                            Surfing
4      [surf]                                            Surfing
5      [fish]                                            Fishing
6       [wad]                                             Wading
7      [swim]                                           Swimming
8      [surf]                                       Kite surfing
9          []                                    Boogie boarding
10     [surf]                                            Surfing
11         []                                      Body boarding
12     [fish]                                       Spearfishing
13     [surf]                                            Surfing
14     [surf]                                            Surfing
15     [surf]                                            Surfing
16      [wad]                                             Wading
17         []                                         Snorkeling
18         []                                  SUP Foil boarding
19     [surf]                                            Surfing
20     [swim]                                           Swimming
21     [swim]                                           Swimming
22         []                                           Kayaking
23         []                                         Lobstering
24     [surf]                                            Surfing
25     [surf]                                            Surfing
26     [surf]                                            Surfing
27     [fish]                                       Spearfishing
28     [fish]                                            Fishing
29     [fish]              Fishing in Alabama Deep Fishing Rodeo
...       ...                                                ...
5835   [swim]                                           Swimming
5836       []                                                NaN
5837   [surf]                                            Surfing
5838       []                                             Murder
5839       []                                                NaN
5840   [fish]                                            Fishing
5841   [bath]                                            Bathing
5842   [swim]                                           Swimming
5843  [shark]  Fell overboard from a frigate & was swallowed ...
5844   [swim]                                           Swimming
5845       []                                                NaN
5846    [div]                                       Pearl diving
5847   [swim]                                           Swimming
5848   [swim]                                           Swimming
5849       []                                                NaN
5850   [swim]                                           Swimming
5851   [swim]                                           Swimming
5852       []                                                NaN
5853   [bath]                                            Bathing
5854   [bath]                                            Bathing
5855       []                                     Went overboard
5856       []                                                NaN
5857    [wad]                                             Wading
5858       []                                                NaN
5859   [swim]                                          Swimming
5860       []  Ship lay at anchor & man was working on its ru...
5861       []  Man fell overboard from ship. Those on board t...
5862   [swim]                                           Swimming
5863       []                                                NaN
5864    [div]                                       Pearl diving

[5865 rows x 2 columns]

In [50]:
df3.columns
# Species, Injury, Fatal, Type, Sex - remaining for cleaning 
#the rest not interesting drop it

Index(['Case Number', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Month', 'new act'],
      dtype='object')