# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [57]:
#Import your libraries

import numpy as np
import pandas as pd

# Introduction

In this lab, we will use two datasets. Both datasets contain variables that describe apps from the Google Play Store. We will use our knowledge in feature extraction to process these datasets and prepare them for the use of a ML algorithm.

# Challenge 1 - Loading and Extracting Features from the First Dataset

#### In this challenge, our goals are: 

* Exploring the dataset.
* Identify the columns with missing values.
* Either replacing the missing values in each column or drop the columns.
* Conver each column to the appropriate type.

#### The first dataset contains different information describing the apps. 

Load the dataset into the variable `google_play` in the cell below. The dataset is in the file `googleplaystore.csv`

In [58]:
# Your code here:

google_play = pd.read_csv('../googleplaystore.csv')

#### Examine all variables and their types in the following cell

In [59]:
# Your code here:
google_play.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
App               10841 non-null object
Category          10841 non-null object
Rating            9367 non-null float64
Reviews           10841 non-null object
Size              10841 non-null object
Installs          10841 non-null object
Type              10840 non-null object
Price             10841 non-null object
Content Rating    10840 non-null object
Genres            10841 non-null object
Last Updated      10841 non-null object
Current Ver       10833 non-null object
Android Ver       10838 non-null object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [60]:
google_play.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#### Since this dataset only contains one numeric column, let's skip the `describe()` function and look at the first 5 rows using the `head()` function

In [61]:
# Your code here:

#### We can see that there are a few columns that could be coerced to numeric.

Start with the reviews column. We can evaluate what value is causing this column to be of object type finding the non-numeric values in this column. To do this, we recall the `to_numeric()` function. With this function, we are able to coerce all non-numeric data to null. We can then use the `isnull()` function to subset our dataframe using the True/False column that this function generates.

In the cell below, transform the Reviews column to numeric and assign this new column to the variable `Reviews_numeric`. Make sure to coerce the errors.

In [62]:
# Your code here:
google_play['Reviews_numeric']=pd.to_numeric(google_play['Reviews'],errors='coerce')

Next, create a column containing True/False values using the `isnull()` function. Assign this column to the `Reviews_isnull` variable.

In [63]:
# Your code here:
google_play['Reviews_isnull']=google_play['Reviews_numeric'].isnull()

In [64]:
google_play['Reviews_isnull']

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
10811    False
10812    False
10813    False
10814    False
10815    False
10816    False
10817    False
10818    False
10819    False
10820    False
10821    False
10822    False
10823    False
10824    False
10825    False
10826    False
10827    False
10828    False
10829    False
10830    False
10831    False
10832    False
10833    False
10834    False
10835    False
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews_isnull, Length: 10841, dtype: bool

In [65]:
google_play['Reviews_isnull'][0]

False

Finally, subset the `google_play` with `Reviews_isnull`. This should give you all the rows that contain non-numeric characters.

Your output should look like:

![Reviews_bool.png](reviews-bool.png)

In [66]:
# Your code here:
google_play.loc[(google_play['Reviews_isnull'] ==True)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

#### We see that Google Play is using a shorthand for millions. 

Let's write a function to transform this data.

Steps:

1. Create a function that returns the correct numeric values of *Reviews*.
1. Define a test string with `M` in the last character.
1. Test your function with the test string. Make sure your function works correctly. If not, modify your functions and test again.

In [67]:
google_play.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0,False

In [68]:
# Your code here
import re

def convert_string_to_numeric(s):
    """
    Convert a string value to numeric. If the last character of the string is `M`, obtain the 
    numeric part of the string, multiply it with 1,000,000, then return the result. Otherwise, 
    convert the string to numeric value and return the result.
    
    Args:
        s: The Reviews score in string format.

    Returns:
        The correct numeric value of the Reviews score.
    """
#     for i in s: => not needed as .apply func loop through all values of the col
    if s[-1]=='M':
        x= (s.strip('M'))
        y = float(x)*1000000       
    else:
        y = float(s)
    return y


# s = '3.0M'

# convert_string_to_numeric(s)

In [69]:
google_play.Reviews=google_play.Reviews.apply(convert_string_to_numeric)
google_play.Reviews

0           159.0
1           967.0
2         87510.0
3        215644.0
4           967.0
5           167.0
6           178.0
7         36815.0
8         13791.0
9           121.0
10        13880.0
11         8788.0
12        44829.0
13         4326.0
14         1518.0
15           55.0
16         3632.0
17           27.0
18       194216.0
19       224399.0
20          450.0
21          654.0
22         7699.0
23           61.0
24          118.0
25          192.0
26        20260.0
27          203.0
28          136.0
29          223.0
           ...
10811         4.0
10812        80.0
10813        20.0
10814       785.0
10815      5775.0
10816         2.0
10817       885.0
10818        96.0
10819        52.0
10820        22.0
10821         6.0
10822         0.0
10823         1.0
10824        67.0
10825         7.0
10826     88486.0
10827       117.0
10828       291.0
10829       603.0
10830       881.0
10831        38.0
10832      1195.0
10833        44.0
10834         7.0
10835         0.0
10836        38.0
10837         4.0
10838         3.0
10839       114.0
10840    398307.0
Name: Reviews, Length: 10841, dtype: float64

The last step is to apply the function to the `Reviews` column in the following cell:

In [70]:
# Your code here:
s = '4.0'
pd.to_numeric(s, errors='coerce')

4.0

Check the non-numeric `Reviews` row again. It should have been fixed now and you should see:

![Reviews_bool_fixed.png](reviews-bool-fixed.png)

In [71]:
# Your code here
google_play.loc[(google_play['Reviews'] == '3.0M')]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver, Reviews_numeric, Reviews_isnull]
Index: []

In [72]:
google_play.loc[(google_play['Reviews_isnull'] ==True)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3000000.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

Also check the variable types of `google_play`. The `Reviews` column should be a `float64` type now.

In [73]:
# Your code here:
google_play.Reviews.dtypes

dtype('float64')

#### The next column we will look at is `Size`. We start by looking at all unique values in `Size`:

*Hint: use `unique()` ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html))*.

In [74]:
# Your code here:
google_play.Size.unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

You should have seen lots of unique values of the app sizes.

#### While we can convert most of the `Size` values to numeric in the same way we converted the `Reviews` values, there is one value that is impossible to convert.

What is that badass value? Enter it in the next cell and calculate the proportion of its occurence to the total number of records of `google_play`.

In [75]:
# Your code here:

#### While this column may be useful for other types of analysis, we opt to drop it from our dataset. 

There are two reasons. First, the majority of the data are ordinal but a sizeable proportion are missing because we cannot convert them to numerical values. Ordinal data are both numerical and categorical, and they usually can be ranked (e.g. 82k is smaller than 91M). In contrast, non-ordinal categorical data such as blood type and eye color cannot be ranked. The second reason is as a categorical column, it has too many unique values to produce meaningful insights. Therefore, in our case the simplest strategy would be to drop the column.

Drop the column in the cell below (use `inplace=True`)

In [76]:
# Your code here:
google_play.drop(['Size'], axis=1, inplace=True)

#### Now let's look at how many missing values are in each column. 

This will give us an idea of whether we should come up with a missing data strategy or give up on the column all together. In the next column, find the number of missing values in each column: 

*Hint: use the `isna()` and `sum()` functions.*

In [77]:
# Your code here:
google_play.isna().sum()

App                   0
Category              0
Rating             1474
Reviews               0
Installs              0
Type                  1
Price                 0
Content Rating        1
Genres                0
Last Updated          0
Current Ver           8
Android Ver           3
Reviews_numeric       1
Reviews_isnull        0
dtype: int64

You should find the column with the most missing values is now `Rating`.

#### What is the proportion of the missing values in `Rating` to the total number of records?

Enter your answer in the cell below.

In [78]:
# Your code here:
round((google_play.Rating.isna().sum()/google_play.shape[0])*100,3)

13.597

In [79]:
google_play.shape[0]

10841

A sizeable proportion of the `Rating` column is missing. A few other columns also contain several missing values.

#### We opt to preserve these columns and remove the rows containing missing data.

In particular, we don't want to drop the `Rating` column because:

* It is one of the most important columns in our dataset. 

* Since the dataset is not a time series, the loss of these rows will not have a negative impact on our ability to analyze the data. It will, however, cause us to lose some meaningful observations. But the loss is limited compared to the gain we receive by preserving these columns.

In the cell below, remove all rows containing at least one missing value. Use the `dropna()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)). Assign the new dataframe to the variable `google_missing_removed`.

In [80]:
# Your code here:
google_missing_removed=google_play.dropna()

In [81]:
google_missing_removed.isna().sum()

App                0
Category           0
Rating             0
Reviews            0
Installs           0
Type               0
Price              0
Content Rating     0
Genres             0
Last Updated       0
Current Ver        0
Android Ver        0
Reviews_numeric    0
Reviews_isnull     0
dtype: int64

From now on, we use the `google_missing_removed` variable instead of `google_play`.

#### Next, we look at the `Last Updated` column.

The `Last Updated` column seems to contain a date, though it is classified as an object type. Let's convert this column using the `pd.to_datetime` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)).

In [82]:
# Your code here:
google_missing_removed['Last Updated']=pd.to_datetime(google_missing_removed['Last Updated'])

C:\Users\anast\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [83]:
google_missing_removed['Last Updated'].head()

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated, dtype: datetime64[ns]

#### The last column we will transform is `Price`. 

We start by looking at the unique values of this column.

In [84]:
# Your code here:
google_missing_removed.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

Since all prices are ordinal data without exceptions, we can tranform this column by removing the dollar sign and converting to numeric. We can create a new column called `Price Numerical` and drop the original column.

We will achieve our goal in three steps. Follow the instructions of each step below.

#### First we remove the dollar sign. Do this in the next cell by applying the `str.replace` function to the column to replace `$` with an empty string (`''`).

In [85]:
# Your code here:
google_missing_removed.Price=google_missing_removed.Price.str.replace('$','')

#### Second step, coerce the `Price Numerical` column to numeric.

In [86]:
# Your code here:
google_missing_removed['Price_numerical']=pd.to_numeric(google_missing_removed.Price, errors='coerce')

C:\Users\anast\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [87]:
google_missing_removed.Price_numerical.dtypes

dtype('float64')

In [88]:
google_missing_removed.Price_numerical.unique()

array([  0.  ,   4.99,   3.99,   6.99,   7.99,   5.99,   2.99,   3.49,
         1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,  24.99,
        11.99,  79.99,  16.99,  14.99,  29.99,  12.99,   2.49,  10.99,
         1.5 ,  19.99,  15.99,  33.99,  39.99,   3.95,   4.49,   1.7 ,
         8.99,   1.49,   3.88, 399.99,  17.99, 400.  ,   3.02,   1.76,
         4.84,   4.77,   1.61,   2.5 ,   1.59,   6.49,   1.29, 299.99,
       379.99,  37.99,  18.99, 389.99,   8.49,   1.75,  14.  ,   2.  ,
         3.08,   2.59,  19.4 ,   3.9 ,   4.59,  15.46,   3.04,  13.99,
         4.29,   3.28,   4.6 ,   1.  ,   2.95,   2.9 ,   1.97,   2.56,
         1.2 ])

In [89]:
google_missing_removed.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull,Price_numerical
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,159.0,False,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,967.0,False,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,87510.0,False,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,215644.0,False,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,967.0,False,0.0

**Finally, drop the original `Price` column.**

In [105]:
# Your code here:
google_missing_removed.drop(['Price'], axis=1, inplace=True)

In [106]:
google_missing_removed.head()

,App,Category,Rating,Reviews,Installs,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull,Price_numerical
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,159.0,False,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,967.0,False,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,87510.0,False,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,215644.0,False,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,967.0,False,0.0

Now check the variable types of `google_missing_removed`. Make sure:

* `Size` and `Price` columns have been removed.
* `Rating`, `Reviews`, and `Price Numerical` have the type of `float64`.
* `Last Updated` has the type of `datetime64`.

In [92]:
# Your code here
google_missing_removed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9360 entries, 0 to 10840
Data columns (total 15 columns):
App                9360 non-null object
Category           9360 non-null object
Rating             9360 non-null float64
Reviews            9360 non-null float64
Installs           9360 non-null object
Type               9360 non-null object
Price              9360 non-null object
Content Rating     9360 non-null object
Genres             9360 non-null object
Last Updated       9360 non-null datetime64[ns]
Current Ver        9360 non-null object
Android Ver        9360 non-null object
Reviews_numeric    9360 non-null float64
Reviews_isnull     9360 non-null bool
Price_numerical    9360 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(9)
memory usage: 1.1+ MB

# Challenge 2 - Loading and Extracting Features from the Second Dataset

Load the second dataset to the variable `google_reviews`. The data is in the file `googleplaystore_user_reviews.csv`.

In [204]:
# Your code here:

google_review = pd.read_csv('../googleplaystore_user_reviews.csv')

#### This dataset contains the top 100 reviews for each app. 

Let's examine this dataset using the `head` function

In [205]:
# Your code here
google_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#### The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app. 

Columns like `Sentiment_Polarity` and `Sentiment_Subjectivity` are not to our interests because we have no clue how to use them. We do not care about `Translated_Review` because natural language processing is too complex for us at present (in fact the `Sentiment`, `Sentiment_Polarity`, and `Sentiment_Subjectivity` columns are derived from `Translated_Review` the data scientists). 

What we care about in this challenge is `Sentiment`. To be more precise, we care about **what is the proportion of *Positive* sentiment of each app**. This will require us to aggregate the `Sentiment` data by `App` in order to calculate the proportions.

Now that you are clear about what we are trying to achieve, follow the steps below that will walk you through towards our goal.

#### Our first step will be to remove all rows with missing sentiment. 

In the next cell, drop all rows with missing data using the `dropna()` function and assign this new dataframe to `review_missing_removed`.

In [206]:
# Your code here:

review_missing_removed=google_review.dropna()

#### Now, use the `value_counts()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) to get a sense on how many apps are in this dataset and their review counts.

In [207]:
# Your code here:
review_missing_removed.App.value_counts()

Bowmasters                                            312
Angry Birds Classic                                   273
Helix Jump                                            273
Calorie Counter - MyFitnessPal                        254
Duolingo: Learn Languages Free                        240
Candy Crush Saga                                      240
Garena Free Fire                                      222
8 Ball Pool                                           219
Calorie Counter - Macros                              200
10 Best Foods for You                                 194
CBS Sports App - Scores, News, Stats & Watch Live     192
Google Photos                                         191
Alto's Adventure                                      175
8fit Workouts & Meal Planner                          171
DRAGON BALL LEGENDS                                   167
Candy Crush Soda Saga                                 166
Clash Royale                                          165
Adobe Acrobat Reader                                  162
Episode - Choose Your Story                           160
Flow Free                                             154
Block Puzzle                                          154
Bubble Shooter                                        145
Calorie Counter - MyNetDiary                          139
Agar.io                                               136
Calorie Counter & Diet Tracker                        135
Cooking Fever                                         135
Galaxy Attack: Alien Shooter                          134
Colorfy: Coloring Book for Adults - Free              133
Gardenscapes                                          133
Facebook                                              132
                                                     ...
ASUS Quick Memo                                         2
Extreme Car Driving Simulator                           2
CM Browser - Ad Blocker , Fast Download , Privacy       2
Calendar Widget Month + Agenda                          2
Calculator Plus Free                                    2
Drawing for Kids Learning Games for Toddlers age 3      1
Draw A Stickman                                         1
Draw a Stickman: EPIC 2                                 1
HomeWork                                                1
Discover Mobile                                         1
DashClock Widget                                        1
Google Trips - Travel Planner                           1
Google Slides                                           1
Caf - Mon Compte                                        1
CBS News                                                1
Fruit Block - Puzzle Legend                             1
Free Live Talk-Video Call                               1
CallApp: Caller ID, Blocker & Phone Call Recorder       1
GPS Map Free                                            1
Daily Workouts - Exercise Fitness Routine Trainer       1
Draw In                                                 1
Apartment Decorating Ideas                              1
Bed Time Fan - White Noise Sleep Sounds                 1
Calendar+ Schedule Planner App                          1
Best Ovulation Tracker Fertility Calendar App Glow      1
HD Camera                                               1
All-in-One Mahjong 3 FREE                               1
Caller ID +                                             1
Best Fiends - Free Puzzle Game                          1
Calculator - unit converter                             1
Name: App, Length: 865, dtype: int64

#### Now the tough part comes. Let's plan how we will achieve our goal:

1. We will count the number of reviews that contain *Positive* in the `Sentiment` column.

1. We will create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app.

1. We will then loop the new dataframe to calculate the postivie review portion of each app.

#### Step 1: Count the number of positive reviews.

In the following cell, write a function that takes a column and returns the number of times *Positive* appears in the column. 

*Hint: One option is to use the `np.where()` function ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html)).*

In [215]:
# Your code below

def positive_function(x):
    """
    Count how many times the string `Positive` appears in a column (exact string match).
    
    Args:
        x: data column
    
    Returns:
        The number of occurrences of `Positive` in the column data.
    """
    k=np.where(x=='Positive', 1, 0)
    
    return sum(k)

In [209]:
#review_missing_removed['Positive']=review_missing_removed['Sentiment'].apply(positive_function)

C:\Users\anast\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [210]:
#review_missing_removed['Positive']

0        1
1        1
3        1
4        1
5        1
6        1
8        0
9        0
10       1
11       1
12       1
13       1
14       1
16       1
17       1
18       1
19       1
20       1
21       1
22       0
23       1
24       1
25       0
26       1
27       1
28       1
29       0
30       1
31       1
32       0
        ..
64185    0
64186    1
64187    1
64188    0
64189    0
64190    1
64191    1
64192    1
64194    0
64196    0
64197    0
64198    1
64199    0
64200    0
64201    0
64205    0
64207    1
64209    1
64213    0
64215    0
64216    0
64217    1
64218    0
64220    0
64221    1
64222    1
64223    1
64226    0
64227    1
64230    0
Name: Positive, Length: 37427, dtype: int64

In [166]:
#review_missing_removed.drop(['Sentiment'], axis=1, inplace=True)

In [211]:
review_missing_removed.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Positive
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333,1
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462,1
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000,1
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000,1
5,10 Best Foods for You,Best way,Positive,1.00,0.300000,1

In [216]:
review_missing_removed.groupby(['App'])['Sentiment'].agg([positive_function,'count'])

                                                    positive_function  count
App
10 Best Foods for You                                             162    194
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室                                   31     40
11st                                                               23     39
1800 Contacts - Lens Store                                         64     80
1LINE – One Line with One Touch                                    27     38
2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif                   25     32
21-Day Meditation Experience                                       68     80
2Date Dating App, Love and matching                                26     38
2GIS: directory & navigator                                        23     40
2RedBeans                                                          31     39
2ndLine - Second Phone Number                                      17     40
30 Day Fitness Challenge - Workout at Home                         27     31
365Scores - Live Scores                                             5      7
3D Live Neon Weed Launcher                                          2      2
4 in a Row                                                         17     20
4K Wallpapers and Ultra HD Backgrounds                              7      9
591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價房貸查詢                  5     15
591房屋交易-香港                                                          5      9
7 Cups: Anxiety & Stress Chat                                       7      8
7 Day Food Journal Challenge                                        9      9
7 Minute Workout                                                   10     11
7 Weeks - Habit & Goal Tracker                                     10     14
8 Ball Pool                                                       104    219
850 Sports News Digest                                             38     39
8fit Workouts & Meal Planner                                      137    171
95Live -SG#1 Live Streaming App                                    34     78
A Call From Santa Claus!                                           20     34
A Word A Day                                                        3      4
A&E - Watch Full Episodes of TV Shows                              30     38
A+ Gallery - Photos & Videos                                       24     41
...                                                               ...    ...
HipChat - Chat Built for Teams                                     19     66
Hipmunk Hotels & Flights                                           30     35
Hitwe - meet people and chat                                        2      9
Hole19: Golf GPS App, Rangefinder & Scorecard                      18     19
Home Decor Showpiece Art making: Medium Difficulty                 16     25
Home Scouting® MLS Mobile                                          13     32
Home Security Camera WardenCam - reuse old phones                  18     26
Home Street – Home Design Game                                     42     57
Home Workout - No Equipment                                        24     26
Home Workout for Men - Bodybuilding                                22     26
Home workouts - fat burning, abs, legs, arms,chest                  8      8
HomeWork                                                            1      1
Homes.com 🏠 For Sale, Rent                                         11     21
Homescapes                                                         27     52
Homesnap Real Estate & Rentals                                     25     35
Homestyler Interior Design & Decorating Ideas                      19     34
Homework Planner                                                   33     37
Honkai Impact 3rd                                                  54     76
Hopper - Watch & Book Flights                                      54     76
Horoscopes – Daily Zodiac Horoscope and Astrology                  21     35
Horses Live Wallpaper                                              22     33
Hostelworld: Hostels & Cheap Hotels Travel App                     42     65
Hot Wheels: Race Off                                               14     20
HotelTonight: Book amazing deals at great hotels                   93    127
Hotels Combined - Cheap deals                                      15     36
Hotels.com: Book Hotel Rooms & Find Vacation Deals                 39     68
Hotspot Shield Free VPN Proxy & Wi-Fi Security                     17     34
Hotstar                                                            14     32
Hotwire Hotel & Car Rental App                                     16     33
Housing-Real Estate & Property                                      8     21

[865 rows x 2 columns]

#### Step 2: Create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app

We will group `review_missing_removed` by the `App` column, then aggregate the grouped dataframe on the number of positive reviews and the total review counts of each app. The result will be assigned to a new variable `google_agg`. Here is the ([documentation on how to achieve it](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). Take a moment or two to read the documentation and google examples because it is pretty complex.

When you obtain `google_agg`, check its values to make sure it has an `App` column as its index as well as a `Positive` column and a `Total` column. Your output should look like:

![Positive Reviews Agg](positive-review-agg.png)

*Hint: Use `positive_function` you created earlier as part of the param passed to the `agg()` function in order to aggregate the number of positive reviews.*

#### Bonus:

As of Pandas v0.23.4, you may opt to supply an array or an object to `agg()`. If you use the array param, you'll need to rename the columns so that their names are `Positive` and `Total`. Using the object param will allow you to create the aggregated columns with the desirable names without renaming them. However, you will probably encounter a warning indicating supplying an object to `agg()` will become outdated. It's up to you which way you will use. Try both ways out. Any way is fine as long as it works.

In [217]:
# Your code here:
google_agg=review_missing_removed.groupby(['App'])['Sentiment'].agg({'Positive':positive_function,'Total':'count'})

C:\Users\anast\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version

Print the first 5 rows of `google_agg` to check it.

In [218]:
# Your code here
google_agg.head()

                                  Positive  Total
App
10 Best Foods for You                  162    194
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40
11st                                    23     39
1800 Contacts - Lens Store              64     80
1LINE – One Line with One Touch         27     38

#### Add a derived column to `google_agg` that is the ratio of the `Positive` and the `Total` columns. Call this column `Positive Ratio`. 

Make sure to account for the case where the denominator is zero using the `np.where()` function.

In [100]:
# Your code here:

#### Now drop the `Positive` and `Total` columns. Do this with `inplace=True`.

In [101]:
# Your code here:

Print the first 5 rows of `google_agg`. Your output should look like:

![Positive Reviews Agg](positive-review-ratio.png)

In [102]:
# Your code here:

# Challenge 3 - Join the Dataframes

In this part of the lab, we will join the two dataframes and obtain a dataframe that contains features we can use in our ML algorithm.

In the next cell, join the `google_missing_removed` dataframe with the `google_agg` dataframe on the `App` column. Assign this dataframe to the variable `google`.

In [103]:
# Your code here:

#### Let's look at the final result using the `head()` function. Your final product should look like:

![Final Product](google-final-head.png)

In [104]:
# Your code here: